// SPDX-License-Identifier: MPL-2.0 · Copyright (c) Aurelian-Risk
// The TTP reference (tactics, techniques): the Enterprise matrix's tactics in its order, and every live technique and sub-technique with the tactics it appears under. Powers the kill-chain typeahead and the tactic vocabulary.
//
// Generated from the ATT&CK STIX bundle (enterprise-attack, version 19.2) by
// scripts/attack-gen.mjs; regenerate rather than edit.
//
// Attribution: the identifiers and names are MITRE ATT&CK® content, © The MITRE
// Corporation, reproduced under the ATT&CK terms of use
// (https://attack.mitre.org/resources/legal-and-branding/terms-of-use/). MITRE ATT&CK® is
// a registered trademark of The MITRE Corporation; this project is not affiliated with or
// endorsed by MITRE. See NOTICE. (Surfaced in the UI generically as "TTP".)

export const ATTACK_VERSION = "19.2";

/** The tactics, in matrix order - also the `tactic` vocabulary of the kill-chain step. */
export const TACTICS: readonly string[] = [
  "Reconnaissance",
  "Resource Development",
  "Initial Access",
  "Execution",
  "Persistence",
  "Privilege Escalation",
  "Stealth",
  "Defense Impairment",
  "Credential Access",
  "Discovery",
  "Lateral Movement",
  "Collection",
  "Command and Control",
  "Exfiltration",
  "Impact",
];

/** The kill-chain phase name a STIX object carries, to the tactic's name. */
export const TACTIC_OF_PHASE: Record<string, string> = {
  "reconnaissance": "Reconnaissance",
  "resource-development": "Resource Development",
  "initial-access": "Initial Access",
  "execution": "Execution",
  "persistence": "Persistence",
  "privilege-escalation": "Privilege Escalation",
  "stealth": "Stealth",
  "defense-impairment": "Defense Impairment",
  "credential-access": "Credential Access",
  "discovery": "Discovery",
  "lateral-movement": "Lateral Movement",
  "collection": "Collection",
  "command-and-control": "Command and Control",
  "exfiltration": "Exfiltration",
  "impact": "Impact",
};

/** Tactics earlier ATT&CK versions had and this one does not, with what took their place.
 *  A step recorded under a retired tactic keeps it until the analyst chooses; a feed still
 *  using the old phase name is read to the first successor. Maintained by hand in the
 *  generator: the bundle does not say what replaced what. */
export const RETIRED_TACTICS: Record<string, readonly string[]> = {
  "Defense Evasion": ["Stealth", "Defense Impairment"],   // split in ATT&CK v19 (2026)
};

export interface Technique {
  id: string; name: string; tactics: readonly string[];
  /** Set on a technique ATT&CK has revoked: the live technique that replaced it. */
  revokedBy?: string;
}

/** Every live technique and sub-technique, by id, plus the revoked ones with their
 *  successor. A sub-technique is named after its technique, as ATT&CK writes it
 *  ("Phishing: Spearphishing Attachment"). */
export const MITRE_TECHNIQUES: readonly Technique[] = [
  { id: "T1001", name: "Data Obfuscation", tactics: ["Command and Control"] },
  { id: "T1001.001", name: "Data Obfuscation: Junk Data", tactics: ["Command and Control"] },
  { id: "T1001.002", name: "Data Obfuscation: Steganography", tactics: ["Command and Control"] },
  { id: "T1001.003", name: "Data Obfuscation: Protocol or Service Impersonation", tactics: ["Command and Control"] },
  { id: "T1002", name: "Data Compressed", tactics: [], revokedBy: "T1560" },
  { id: "T1003", name: "OS Credential Dumping", tactics: ["Credential Access"] },
  { id: "T1003.001", name: "OS Credential Dumping: LSASS Memory", tactics: ["Credential Access"] },
  { id: "T1003.002", name: "OS Credential Dumping: Security Account Manager", tactics: ["Credential Access"] },
  { id: "T1003.003", name: "OS Credential Dumping: NTDS", tactics: ["Credential Access"] },
  { id: "T1003.004", name: "OS Credential Dumping: LSA Secrets", tactics: ["Credential Access"] },
  { id: "T1003.005", name: "OS Credential Dumping: Cached Domain Credentials", tactics: ["Credential Access"] },
  { id: "T1003.006", name: "OS Credential Dumping: DCSync", tactics: ["Credential Access"] },
  { id: "T1003.007", name: "OS Credential Dumping: Proc Filesystem", tactics: ["Credential Access"] },
  { id: "T1003.008", name: "OS Credential Dumping: /etc/passwd and /etc/shadow", tactics: ["Credential Access"] },
  { id: "T1004", name: "Winlogon Helper DLL", tactics: [], revokedBy: "T1547.004" },
  { id: "T1005", name: "Data from Local System", tactics: ["Collection"] },
  { id: "T1006", name: "Direct Volume Access", tactics: ["Stealth"] },
  { id: "T1007", name: "System Service Discovery", tactics: ["Discovery"] },
  { id: "T1008", name: "Fallback Channels", tactics: ["Command and Control"] },
  { id: "T1009", name: "Binary Padding", tactics: [], revokedBy: "T1027.001" },
  { id: "T1010", name: "Application Window Discovery", tactics: ["Discovery"] },
  { id: "T1011", name: "Exfiltration Over Other Network Medium", tactics: ["Exfiltration"] },
  { id: "T1011.001", name: "Exfiltration Over Other Network Medium: Exfiltration Over Bluetooth", tactics: ["Exfiltration"] },
  { id: "T1012", name: "Query Registry", tactics: ["Discovery"] },
  { id: "T1013", name: "Port Monitors", tactics: [], revokedBy: "T1547.010" },
  { id: "T1014", name: "Rootkit", tactics: ["Stealth"] },
  { id: "T1015", name: "Accessibility Features", tactics: [], revokedBy: "T1546.008" },
  { id: "T1016", name: "System Network Configuration Discovery", tactics: ["Discovery"] },
  { id: "T1016.001", name: "System Network Configuration Discovery: Internet Connection Discovery", tactics: ["Discovery"] },
  { id: "T1016.002", name: "System Network Configuration Discovery: Wi-Fi Discovery", tactics: ["Discovery"] },
  { id: "T1017", name: "Application Deployment Software", tactics: [], revokedBy: "T1072" },
  { id: "T1018", name: "Remote System Discovery", tactics: ["Discovery"] },
  { id: "T1019", name: "System Firmware", tactics: [], revokedBy: "T1542.001" },
  { id: "T1020", name: "Automated Exfiltration", tactics: ["Exfiltration"] },
  { id: "T1020.001", name: "Automated Exfiltration: Traffic Duplication", tactics: ["Exfiltration"] },
  { id: "T1021", name: "Remote Services", tactics: ["Lateral Movement"] },
  { id: "T1021.001", name: "Remote Services: Remote Desktop Protocol", tactics: ["Lateral Movement"] },
  { id: "T1021.002", name: "Remote Services: SMB/Windows Admin Shares", tactics: ["Lateral Movement"] },
  { id: "T1021.003", name: "Remote Services: Distributed Component Object Model", tactics: ["Lateral Movement"] },
  { id: "T1021.004", name: "Remote Services: SSH", tactics: ["Lateral Movement"] },
  { id: "T1021.005", name: "Remote Services: VNC", tactics: ["Lateral Movement"] },
  { id: "T1021.006", name: "Remote Services: Windows Remote Management", tactics: ["Lateral Movement"] },
  { id: "T1021.007", name: "Remote Services: Cloud Services", tactics: ["Lateral Movement"] },
  { id: "T1021.008", name: "Remote Services: Direct Cloud VM Connections", tactics: ["Lateral Movement"] },
  { id: "T1022", name: "Data Encrypted", tactics: [], revokedBy: "T1560" },
  { id: "T1023", name: "Shortcut Modification", tactics: [], revokedBy: "T1547.009" },
  { id: "T1024", name: "Custom Cryptographic Protocol", tactics: [], revokedBy: "T1573" },
  { id: "T1025", name: "Data from Removable Media", tactics: ["Collection"] },
  { id: "T1027", name: "Obfuscated Files or Information", tactics: ["Stealth"] },
  { id: "T1027.001", name: "Obfuscated Files or Information: Binary Padding", tactics: ["Stealth"] },
  { id: "T1027.002", name: "Obfuscated Files or Information: Software Packing", tactics: ["Stealth"] },
  { id: "T1027.003", name: "Obfuscated Files or Information: Steganography", tactics: ["Stealth"] },
  { id: "T1027.004", name: "Obfuscated Files or Information: Compile After Delivery", tactics: ["Stealth"] },
  { id: "T1027.005", name: "Obfuscated Files or Information: Indicator Removal from Tools", tactics: ["Stealth"] },
  { id: "T1027.006", name: "Obfuscated Files or Information: HTML Smuggling", tactics: ["Stealth"] },
  { id: "T1027.007", name: "Obfuscated Files or Information: Dynamic API Resolution", tactics: ["Stealth"] },
  { id: "T1027.008", name: "Obfuscated Files or Information: Stripped Payloads", tactics: ["Stealth"] },
  { id: "T1027.009", name: "Obfuscated Files or Information: Embedded Payloads", tactics: ["Stealth"] },
  { id: "T1027.010", name: "Obfuscated Files or Information: Command Obfuscation", tactics: ["Stealth"] },
  { id: "T1027.011", name: "Obfuscated Files or Information: Fileless Storage", tactics: ["Stealth"] },
  { id: "T1027.012", name: "Obfuscated Files or Information: LNK Icon Smuggling", tactics: ["Stealth"] },
  { id: "T1027.013", name: "Obfuscated Files or Information: Encrypted/Encoded File", tactics: ["Stealth"] },
  { id: "T1027.014", name: "Obfuscated Files or Information: Polymorphic Code", tactics: ["Stealth"] },
  { id: "T1027.015", name: "Obfuscated Files or Information: Compression", tactics: ["Stealth"] },
  { id: "T1027.016", name: "Obfuscated Files or Information: Junk Code Insertion", tactics: ["Stealth"] },
  { id: "T1027.017", name: "Obfuscated Files or Information: SVG Smuggling", tactics: ["Stealth"] },
  { id: "T1027.018", name: "Obfuscated Files or Information: Invisible Unicode", tactics: ["Stealth"] },
  { id: "T1028", name: "Windows Remote Management", tactics: [], revokedBy: "T1021.006" },
  { id: "T1029", name: "Scheduled Transfer", tactics: ["Exfiltration"] },
  { id: "T1030", name: "Data Transfer Size Limits", tactics: ["Exfiltration"] },
  { id: "T1031", name: "Modify Existing Service", tactics: [], revokedBy: "T1543.003" },
  { id: "T1032", name: "Standard Cryptographic Protocol", tactics: [], revokedBy: "T1573" },
  { id: "T1033", name: "System Owner/User Discovery", tactics: ["Discovery"] },
  { id: "T1035", name: "Service Execution", tactics: [], revokedBy: "T1569.002" },
  { id: "T1036", name: "Masquerading", tactics: ["Stealth"] },
  { id: "T1036.001", name: "Masquerading: Invalid Code Signature", tactics: ["Stealth"] },
  { id: "T1036.002", name: "Masquerading: Right-to-Left Override", tactics: ["Stealth"] },
  { id: "T1036.003", name: "Masquerading: Rename Legitimate Utilities", tactics: ["Stealth"] },
  { id: "T1036.004", name: "Masquerading: Masquerade Task or Service", tactics: ["Stealth"] },
  { id: "T1036.005", name: "Masquerading: Match Legitimate Resource Name or Location", tactics: ["Stealth"] },
  { id: "T1036.006", name: "Masquerading: Space after Filename", tactics: ["Stealth"] },
  { id: "T1036.007", name: "Masquerading: Double File Extension", tactics: ["Stealth"] },
  { id: "T1036.008", name: "Masquerading: Masquerade File Type", tactics: ["Stealth"] },
  { id: "T1036.009", name: "Masquerading: Break Process Trees", tactics: ["Stealth"] },
  { id: "T1036.010", name: "Masquerading: Masquerade Account Name", tactics: ["Stealth"] },
  { id: "T1036.011", name: "Masquerading: Overwrite Process Arguments", tactics: ["Stealth"] },
  { id: "T1036.012", name: "Masquerading: Browser Fingerprint", tactics: ["Stealth"] },
  { id: "T1037", name: "Boot or Logon Initialization Scripts", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1037.001", name: "Boot or Logon Initialization Scripts: Logon Script (Windows)", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1037.002", name: "Boot or Logon Initialization Scripts: Login Hook", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1037.003", name: "Boot or Logon Initialization Scripts: Network Logon Script", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1037.004", name: "Boot or Logon Initialization Scripts: RC Scripts", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1037.005", name: "Boot or Logon Initialization Scripts: Startup Items", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1038", name: "DLL Search Order Hijacking", tactics: [], revokedBy: "T1574.001" },
  { id: "T1039", name: "Data from Network Shared Drive", tactics: ["Collection"] },
  { id: "T1040", name: "Network Sniffing", tactics: ["Credential Access", "Discovery"] },
  { id: "T1041", name: "Exfiltration Over C2 Channel", tactics: ["Exfiltration"] },
  { id: "T1042", name: "Change Default File Association", tactics: [], revokedBy: "T1546.001" },
  { id: "T1044", name: "File System Permissions Weakness", tactics: [], revokedBy: "T1574.010" },
  { id: "T1045", name: "Software Packing", tactics: [], revokedBy: "T1027.002" },
  { id: "T1046", name: "Network Service Discovery", tactics: ["Discovery"] },
  { id: "T1047", name: "Windows Management Instrumentation", tactics: ["Execution"] },
  { id: "T1048", name: "Exfiltration Over Alternative Protocol", tactics: ["Exfiltration"] },
  { id: "T1048.001", name: "Exfiltration Over Alternative Protocol: Exfiltration Over Symmetric Encrypted Non-C2 Protocol", tactics: ["Exfiltration"] },
  { id: "T1048.002", name: "Exfiltration Over Alternative Protocol: Exfiltration Over Asymmetric Encrypted Non-C2 Protocol", tactics: ["Exfiltration"] },
  { id: "T1048.003", name: "Exfiltration Over Alternative Protocol: Exfiltration Over Unencrypted Non-C2 Protocol", tactics: ["Exfiltration"] },
  { id: "T1049", name: "System Network Connections Discovery", tactics: ["Discovery"] },
  { id: "T1050", name: "New Service", tactics: [], revokedBy: "T1543.003" },
  { id: "T1052", name: "Exfiltration Over Physical Medium", tactics: ["Exfiltration"] },
  { id: "T1052.001", name: "Exfiltration Over Physical Medium: Exfiltration over USB", tactics: ["Exfiltration"] },
  { id: "T1053", name: "Scheduled Task/Job", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1053.001", name: "At (Linux)", tactics: [], revokedBy: "T1053.002" },
  { id: "T1053.002", name: "Scheduled Task/Job: At", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1053.003", name: "Scheduled Task/Job: Cron", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1053.005", name: "Scheduled Task/Job: Scheduled Task", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1053.006", name: "Scheduled Task/Job: Systemd Timers", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1053.007", name: "Scheduled Task/Job: Container Orchestration Job", tactics: ["Execution", "Persistence", "Privilege Escalation"] },
  { id: "T1054", name: "Indicator Blocking", tactics: [], revokedBy: "T1685" },
  { id: "T1055", name: "Process Injection", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.001", name: "Process Injection: Dynamic-link Library Injection", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.002", name: "Process Injection: Portable Executable Injection", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.003", name: "Process Injection: Thread Execution Hijacking", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.004", name: "Process Injection: Asynchronous Procedure Call", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.005", name: "Process Injection: Thread Local Storage", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.008", name: "Process Injection: Ptrace System Calls", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.009", name: "Process Injection: Proc Memory", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.011", name: "Process Injection: Extra Window Memory Injection", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.012", name: "Process Injection: Process Hollowing", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.013", name: "Process Injection: Process Doppelgänging", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.014", name: "Process Injection: VDSO Hijacking", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1055.015", name: "Process Injection: ListPlanting", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1056", name: "Input Capture", tactics: ["Collection", "Credential Access"] },
  { id: "T1056.001", name: "Input Capture: Keylogging", tactics: ["Collection", "Credential Access"] },
  { id: "T1056.002", name: "Input Capture: GUI Input Capture", tactics: ["Collection", "Credential Access"] },
  { id: "T1056.003", name: "Input Capture: Web Portal Capture", tactics: ["Collection", "Credential Access"] },
  { id: "T1056.004", name: "Input Capture: Credential API Hooking", tactics: ["Collection", "Credential Access"] },
  { id: "T1057", name: "Process Discovery", tactics: ["Discovery"] },
  { id: "T1058", name: "Service Registry Permissions Weakness", tactics: [], revokedBy: "T1574.011" },
  { id: "T1059", name: "Command and Scripting Interpreter", tactics: ["Execution"] },
  { id: "T1059.001", name: "Command and Scripting Interpreter: PowerShell", tactics: ["Execution"] },
  { id: "T1059.002", name: "Command and Scripting Interpreter: AppleScript", tactics: ["Execution"] },
  { id: "T1059.003", name: "Command and Scripting Interpreter: Windows Command Shell", tactics: ["Execution"] },
  { id: "T1059.004", name: "Command and Scripting Interpreter: Unix Shell", tactics: ["Execution"] },
  { id: "T1059.005", name: "Command and Scripting Interpreter: Visual Basic", tactics: ["Execution"] },
  { id: "T1059.006", name: "Command and Scripting Interpreter: Python", tactics: ["Execution"] },
  { id: "T1059.007", name: "Command and Scripting Interpreter: JavaScript", tactics: ["Execution"] },
  { id: "T1059.008", name: "Command and Scripting Interpreter: Network Device CLI", tactics: ["Execution"] },
  { id: "T1059.009", name: "Command and Scripting Interpreter: Cloud API", tactics: ["Execution"] },
  { id: "T1059.010", name: "Command and Scripting Interpreter: AutoHotKey & AutoIT", tactics: ["Execution"] },
  { id: "T1059.011", name: "Command and Scripting Interpreter: Lua", tactics: ["Execution"] },
  { id: "T1059.012", name: "Command and Scripting Interpreter: Hypervisor CLI", tactics: ["Execution"] },
  { id: "T1059.013", name: "Command and Scripting Interpreter: Container CLI/API", tactics: ["Execution"] },
  { id: "T1060", name: "Registry Run Keys / Startup Folder", tactics: [], revokedBy: "T1547.001" },
  { id: "T1063", name: "Security Software Discovery", tactics: [], revokedBy: "T1518.001" },
  { id: "T1065", name: "Uncommonly Used Port", tactics: [], revokedBy: "T1571" },
  { id: "T1066", name: "Indicator Removal from Tools", tactics: [], revokedBy: "T1027.005" },
  { id: "T1067", name: "Bootkit", tactics: [], revokedBy: "T1542.003" },
  { id: "T1068", name: "Exploitation for Privilege Escalation", tactics: ["Privilege Escalation"] },
  { id: "T1069", name: "Permission Groups Discovery", tactics: ["Discovery"] },
  { id: "T1069.001", name: "Permission Groups Discovery: Local Groups", tactics: ["Discovery"] },
  { id: "T1069.002", name: "Permission Groups Discovery: Domain Groups", tactics: ["Discovery"] },
  { id: "T1069.003", name: "Permission Groups Discovery: Cloud Groups", tactics: ["Discovery"] },
  { id: "T1070", name: "Indicator Removal", tactics: ["Stealth"] },
  { id: "T1070.001", name: "Clear Windows Event Logs", tactics: [], revokedBy: "T1685.005" },
  { id: "T1070.002", name: "Clear Linux or Mac System Logs", tactics: [], revokedBy: "T1685.006" },
  { id: "T1070.003", name: "Indicator Removal: Clear Command History", tactics: ["Stealth"] },
  { id: "T1070.004", name: "Indicator Removal: File Deletion", tactics: ["Stealth"] },
  { id: "T1070.005", name: "Indicator Removal: Network Share Connection Removal", tactics: ["Stealth"] },
  { id: "T1070.006", name: "Indicator Removal: Timestomp", tactics: ["Stealth"] },
  { id: "T1070.007", name: "Indicator Removal: Clear Network Connection History and Configurations", tactics: ["Stealth"] },
  { id: "T1070.008", name: "Indicator Removal: Clear Mailbox Data", tactics: ["Stealth"] },
  { id: "T1070.009", name: "Indicator Removal: Clear Persistence", tactics: ["Stealth"] },
  { id: "T1070.010", name: "Indicator Removal: Relocate Malware", tactics: ["Stealth"] },
  { id: "T1071", name: "Application Layer Protocol", tactics: ["Command and Control"] },
  { id: "T1071.001", name: "Application Layer Protocol: Web Protocols", tactics: ["Command and Control"] },
  { id: "T1071.002", name: "Application Layer Protocol: File Transfer Protocols", tactics: ["Command and Control"] },
  { id: "T1071.003", name: "Application Layer Protocol: Mail Protocols", tactics: ["Command and Control"] },
  { id: "T1071.004", name: "Application Layer Protocol: DNS", tactics: ["Command and Control"] },
  { id: "T1071.005", name: "Application Layer Protocol: Publish/Subscribe Protocols", tactics: ["Command and Control"] },
  { id: "T1072", name: "Software Deployment Tools", tactics: ["Execution", "Lateral Movement"] },
  { id: "T1073", name: "DLL Side-Loading", tactics: [], revokedBy: "T1574.001" },
  { id: "T1074", name: "Data Staged", tactics: ["Collection"] },
  { id: "T1074.001", name: "Data Staged: Local Data Staging", tactics: ["Collection"] },
  { id: "T1074.002", name: "Data Staged: Remote Data Staging", tactics: ["Collection"] },
  { id: "T1075", name: "Pass the Hash", tactics: [], revokedBy: "T1550.002" },
  { id: "T1076", name: "Remote Desktop Protocol", tactics: [], revokedBy: "T1021.001" },
  { id: "T1077", name: "Windows Admin Shares", tactics: [], revokedBy: "T1021.002" },
  { id: "T1078", name: "Valid Accounts", tactics: ["Stealth", "Persistence", "Privilege Escalation", "Initial Access"] },
  { id: "T1078.001", name: "Valid Accounts: Default Accounts", tactics: ["Stealth", "Persistence", "Privilege Escalation", "Initial Access"] },
  { id: "T1078.002", name: "Valid Accounts: Domain Accounts", tactics: ["Stealth", "Persistence", "Privilege Escalation", "Initial Access"] },
  { id: "T1078.003", name: "Valid Accounts: Local Accounts", tactics: ["Stealth", "Persistence", "Privilege Escalation", "Initial Access"] },
  { id: "T1078.004", name: "Valid Accounts: Cloud Accounts", tactics: ["Stealth", "Persistence", "Privilege Escalation", "Initial Access"] },
  { id: "T1079", name: "Multilayer Encryption", tactics: [], revokedBy: "T1573" },
  { id: "T1080", name: "Taint Shared Content", tactics: ["Lateral Movement"] },
  { id: "T1081", name: "Credentials in Files", tactics: [], revokedBy: "T1552.001" },
  { id: "T1082", name: "System Information Discovery", tactics: ["Discovery"] },
  { id: "T1083", name: "File and Directory Discovery", tactics: ["Discovery"] },
  { id: "T1084", name: "Windows Management Instrumentation Event Subscription", tactics: [], revokedBy: "T1546.003" },
  { id: "T1085", name: "Rundll32", tactics: [], revokedBy: "T1218.011" },
  { id: "T1086", name: "PowerShell", tactics: [], revokedBy: "T1059.001" },
  { id: "T1087", name: "Account Discovery", tactics: ["Discovery"] },
  { id: "T1087.001", name: "Account Discovery: Local Account", tactics: ["Discovery"] },
  { id: "T1087.002", name: "Account Discovery: Domain Account", tactics: ["Discovery"] },
  { id: "T1087.003", name: "Account Discovery: Email Account", tactics: ["Discovery"] },
  { id: "T1087.004", name: "Account Discovery: Cloud Account", tactics: ["Discovery"] },
  { id: "T1088", name: "Bypass User Account Control", tactics: [], revokedBy: "T1548.002" },
  { id: "T1089", name: "Disabling Security Tools", tactics: [], revokedBy: "T1685" },
  { id: "T1090", name: "Proxy", tactics: ["Command and Control"] },
  { id: "T1090.001", name: "Proxy: Internal Proxy", tactics: ["Command and Control"] },
  { id: "T1090.002", name: "Proxy: External Proxy", tactics: ["Command and Control"] },
  { id: "T1090.003", name: "Proxy: Multi-hop Proxy", tactics: ["Command and Control"] },
  { id: "T1090.004", name: "Proxy: Domain Fronting", tactics: ["Command and Control"] },
  { id: "T1091", name: "Replication Through Removable Media", tactics: ["Lateral Movement", "Initial Access"] },
  { id: "T1092", name: "Communication Through Removable Media", tactics: ["Command and Control"] },
  { id: "T1093", name: "Process Hollowing", tactics: [], revokedBy: "T1055.012" },
  { id: "T1094", name: "Custom Command and Control Protocol", tactics: [], revokedBy: "T1095" },
  { id: "T1095", name: "Non-Application Layer Protocol", tactics: ["Command and Control"] },
  { id: "T1096", name: "NTFS File Attributes", tactics: [], revokedBy: "T1564.004" },
  { id: "T1097", name: "Pass the Ticket", tactics: [], revokedBy: "T1550.003" },
  { id: "T1098", name: "Account Manipulation", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.001", name: "Account Manipulation: Additional Cloud Credentials", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.002", name: "Account Manipulation: Additional Email Delegate Permissions", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.003", name: "Account Manipulation: Additional Cloud Roles", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.004", name: "Account Manipulation: SSH Authorized Keys", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.005", name: "Account Manipulation: Device Registration", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.006", name: "Account Manipulation: Additional Container Cluster Roles", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1098.007", name: "Account Manipulation: Additional Local or Domain Groups", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1099", name: "Timestomp", tactics: [], revokedBy: "T1070.006" },
  { id: "T1100", name: "Web Shell", tactics: [], revokedBy: "T1505.003" },
  { id: "T1101", name: "Security Support Provider", tactics: [], revokedBy: "T1547.005" },
  { id: "T1102", name: "Web Service", tactics: ["Command and Control"] },
  { id: "T1102.001", name: "Web Service: Dead Drop Resolver", tactics: ["Command and Control"] },
  { id: "T1102.002", name: "Web Service: Bidirectional Communication", tactics: ["Command and Control"] },
  { id: "T1102.003", name: "Web Service: One-Way Communication", tactics: ["Command and Control"] },
  { id: "T1103", name: "AppInit DLLs", tactics: [], revokedBy: "T1546.010" },
  { id: "T1104", name: "Multi-Stage Channels", tactics: ["Command and Control"] },
  { id: "T1105", name: "Ingress Tool Transfer", tactics: ["Command and Control"] },
  { id: "T1106", name: "Native API", tactics: ["Execution"] },
  { id: "T1107", name: "File Deletion", tactics: [], revokedBy: "T1070.004" },
  { id: "T1109", name: "Component Firmware", tactics: [], revokedBy: "T1542.002" },
  { id: "T1110", name: "Brute Force", tactics: ["Credential Access"] },
  { id: "T1110.001", name: "Brute Force: Password Guessing", tactics: ["Credential Access"] },
  { id: "T1110.002", name: "Brute Force: Password Cracking", tactics: ["Credential Access"] },
  { id: "T1110.003", name: "Brute Force: Password Spraying", tactics: ["Credential Access"] },
  { id: "T1110.004", name: "Brute Force: Credential Stuffing", tactics: ["Credential Access"] },
  { id: "T1111", name: "Multi-Factor Authentication Interception", tactics: ["Credential Access"] },
  { id: "T1112", name: "Modify Registry", tactics: ["Defense Impairment", "Persistence"] },
  { id: "T1113", name: "Screen Capture", tactics: ["Collection"] },
  { id: "T1114", name: "Email Collection", tactics: ["Collection"] },
  { id: "T1114.001", name: "Email Collection: Local Email Collection", tactics: ["Collection"] },
  { id: "T1114.002", name: "Email Collection: Remote Email Collection", tactics: ["Collection"] },
  { id: "T1114.003", name: "Email Collection: Email Forwarding Rule", tactics: ["Collection"] },
  { id: "T1115", name: "Clipboard Data", tactics: ["Collection"] },
  { id: "T1116", name: "Code Signing", tactics: [], revokedBy: "T1553.002" },
  { id: "T1117", name: "Regsvr32", tactics: [], revokedBy: "T1218.010" },
  { id: "T1118", name: "InstallUtil", tactics: [], revokedBy: "T1218.004" },
  { id: "T1119", name: "Automated Collection", tactics: ["Collection"] },
  { id: "T1120", name: "Peripheral Device Discovery", tactics: ["Discovery"] },
  { id: "T1121", name: "Regsvcs/Regasm", tactics: [], revokedBy: "T1218.009" },
  { id: "T1122", name: "Component Object Model Hijacking", tactics: [], revokedBy: "T1546.015" },
  { id: "T1123", name: "Audio Capture", tactics: ["Collection"] },
  { id: "T1124", name: "System Time Discovery", tactics: ["Discovery"] },
  { id: "T1125", name: "Video Capture", tactics: ["Collection"] },
  { id: "T1126", name: "Network Share Connection Removal", tactics: [], revokedBy: "T1070.005" },
  { id: "T1127", name: "Trusted Developer Utilities Proxy Execution", tactics: ["Stealth", "Execution"] },
  { id: "T1127.001", name: "Trusted Developer Utilities Proxy Execution: MSBuild", tactics: ["Stealth", "Execution"] },
  { id: "T1127.002", name: "Trusted Developer Utilities Proxy Execution: ClickOnce", tactics: ["Stealth", "Execution"] },
  { id: "T1127.003", name: "Trusted Developer Utilities Proxy Execution: JamPlus", tactics: ["Stealth", "Execution"] },
  { id: "T1128", name: "Netsh Helper DLL", tactics: [], revokedBy: "T1546.007" },
  { id: "T1129", name: "Shared Modules", tactics: ["Execution"] },
  { id: "T1130", name: "Install Root Certificate", tactics: [], revokedBy: "T1553.004" },
  { id: "T1131", name: "Authentication Package", tactics: [], revokedBy: "T1547.002" },
  { id: "T1132", name: "Data Encoding", tactics: ["Command and Control"] },
  { id: "T1132.001", name: "Data Encoding: Standard Encoding", tactics: ["Command and Control"] },
  { id: "T1132.002", name: "Data Encoding: Non-Standard Encoding", tactics: ["Command and Control"] },
  { id: "T1133", name: "External Remote Services", tactics: ["Persistence", "Initial Access"] },
  { id: "T1134", name: "Access Token Manipulation", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1134.001", name: "Access Token Manipulation: Token Impersonation/Theft", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1134.002", name: "Access Token Manipulation: Create Process with Token", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1134.003", name: "Access Token Manipulation: Make and Impersonate Token", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1134.004", name: "Access Token Manipulation: Parent PID Spoofing", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1134.005", name: "Access Token Manipulation: SID-History Injection", tactics: ["Stealth", "Privilege Escalation"] },
  { id: "T1135", name: "Network Share Discovery", tactics: ["Discovery"] },
  { id: "T1136", name: "Create Account", tactics: ["Persistence"] },
  { id: "T1136.001", name: "Create Account: Local Account", tactics: ["Persistence"] },
  { id: "T1136.002", name: "Create Account: Domain Account", tactics: ["Persistence"] },
  { id: "T1136.003", name: "Create Account: Cloud Account", tactics: ["Persistence"] },
  { id: "T1137", name: "Office Application Startup", tactics: ["Persistence"] },
  { id: "T1137.001", name: "Office Application Startup: Office Template Macros", tactics: ["Persistence"] },
  { id: "T1137.002", name: "Office Application Startup: Office Test", tactics: ["Persistence"] },
  { id: "T1137.003", name: "Office Application Startup: Outlook Forms", tactics: ["Persistence"] },
  { id: "T1137.004", name: "Office Application Startup: Outlook Home Page", tactics: ["Persistence"] },
  { id: "T1137.005", name: "Office Application Startup: Outlook Rules", tactics: ["Persistence"] },
  { id: "T1137.006", name: "Office Application Startup: Add-ins", tactics: ["Persistence"] },
  { id: "T1138", name: "Application Shimming", tactics: [], revokedBy: "T1546.011" },
  { id: "T1139", name: "Bash History", tactics: [], revokedBy: "T1552.003" },
  { id: "T1140", name: "Deobfuscate/Decode Files or Information", tactics: ["Stealth"] },
  { id: "T1141", name: "Input Prompt", tactics: [], revokedBy: "T1056.002" },
  { id: "T1142", name: "Keychain", tactics: [], revokedBy: "T1555.001" },
  { id: "T1143", name: "Hidden Window", tactics: [], revokedBy: "T1564.003" },
  { id: "T1144", name: "Gatekeeper Bypass", tactics: [], revokedBy: "T1553.001" },
  { id: "T1145", name: "Private Keys", tactics: [], revokedBy: "T1552.004" },
  { id: "T1146", name: "Clear Command History", tactics: [], revokedBy: "T1070.003" },
  { id: "T1147", name: "Hidden Users", tactics: [], revokedBy: "T1564.002" },
  { id: "T1148", name: "HISTCONTROL", tactics: [], revokedBy: "T1690" },
  { id: "T1150", name: "Plist Modification", tactics: [], revokedBy: "T1647" },
  { id: "T1151", name: "Space after Filename", tactics: [], revokedBy: "T1036.006" },
  { id: "T1152", name: "Launchctl", tactics: [], revokedBy: "T1569.001" },
  { id: "T1154", name: "Trap", tactics: [], revokedBy: "T1546.005" },
  { id: "T1155", name: "AppleScript", tactics: [], revokedBy: "T1059.002" },
  { id: "T1156", name: "Malicious Shell Modification", tactics: [], revokedBy: "T1546.004" },
  { id: "T1157", name: "Dylib Hijacking", tactics: [], revokedBy: "T1574.004" },
  { id: "T1158", name: "Hidden Files and Directories", tactics: [], revokedBy: "T1564.001" },
  { id: "T1159", name: "Launch Agent", tactics: [], revokedBy: "T1543.001" },
  { id: "T1160", name: "Launch Daemon", tactics: [], revokedBy: "T1543.004" },
  { id: "T1161", name: "LC_LOAD_DYLIB Addition", tactics: [], revokedBy: "T1546.006" },
  { id: "T1162", name: "Login Item", tactics: [], revokedBy: "T1647" },
  { id: "T1163", name: "Rc.common", tactics: [], revokedBy: "T1037.004" },
  { id: "T1164", name: "Re-opened Applications", tactics: [], revokedBy: "T1547.007" },
  { id: "T1165", name: "Startup Items", tactics: [], revokedBy: "T1037.005" },
  { id: "T1166", name: "Setuid and Setgid", tactics: [], revokedBy: "T1548.001" },
  { id: "T1167", name: "Securityd Memory", tactics: [], revokedBy: "T1555.002" },
  { id: "T1168", name: "Local Job Scheduling", tactics: [], revokedBy: "T1053" },
  { id: "T1169", name: "Sudo", tactics: [], revokedBy: "T1548.003" },
  { id: "T1170", name: "Mshta", tactics: [], revokedBy: "T1218.005" },
  { id: "T1171", name: "LLMNR/NBT-NS Poisoning and Relay", tactics: [], revokedBy: "T1557.001" },
  { id: "T1172", name: "Domain Fronting", tactics: [], revokedBy: "T1090.004" },
  { id: "T1173", name: "Dynamic Data Exchange", tactics: [], revokedBy: "T1559.002" },
  { id: "T1174", name: "Password Filter DLL", tactics: [], revokedBy: "T1556.002" },
  { id: "T1176", name: "Software Extensions", tactics: ["Persistence"] },
  { id: "T1176.001", name: "Software Extensions: Browser Extensions", tactics: ["Persistence"] },
  { id: "T1176.002", name: "Software Extensions: IDE Extensions", tactics: ["Persistence"] },
  { id: "T1177", name: "LSASS Driver", tactics: [], revokedBy: "T1547.008" },
  { id: "T1178", name: "SID-History Injection", tactics: [], revokedBy: "T1134.005" },
  { id: "T1179", name: "Hooking", tactics: [], revokedBy: "T1056.004" },
  { id: "T1180", name: "Screensaver", tactics: [], revokedBy: "T1546.002" },
  { id: "T1181", name: "Extra Window Memory Injection", tactics: [], revokedBy: "T1055.011" },
  { id: "T1182", name: "AppCert DLLs", tactics: [], revokedBy: "T1546.009" },
  { id: "T1183", name: "Image File Execution Options Injection", tactics: [], revokedBy: "T1546.012" },
  { id: "T1184", name: "SSH Hijacking", tactics: [], revokedBy: "T1563.001" },
  { id: "T1185", name: "Browser Session Hijacking", tactics: ["Collection"] },
  { id: "T1186", name: "Process Doppelgänging", tactics: [], revokedBy: "T1055.013" },
  { id: "T1187", name: "Forced Authentication", tactics: ["Credential Access"] },
  { id: "T1188", name: "Multi-hop Proxy", tactics: [], revokedBy: "T1090.003" },
  { id: "T1189", name: "Drive-by Compromise", tactics: ["Initial Access"] },
  { id: "T1190", name: "Exploit Public-Facing Application", tactics: ["Initial Access"] },
  { id: "T1191", name: "CMSTP", tactics: [], revokedBy: "T1218.003" },
  { id: "T1192", name: "Spearphishing Link", tactics: [], revokedBy: "T1566.002" },
  { id: "T1193", name: "Spearphishing Attachment", tactics: [], revokedBy: "T1566.001" },
  { id: "T1194", name: "Spearphishing via Service", tactics: [], revokedBy: "T1566.003" },
  { id: "T1195", name: "Supply Chain Compromise", tactics: ["Initial Access"] },
  { id: "T1195.001", name: "Supply Chain Compromise: Compromise Software Dependencies and Development Tools", tactics: ["Initial Access"] },
  { id: "T1195.002", name: "Supply Chain Compromise: Compromise Software Supply Chain", tactics: ["Initial Access"] },
  { id: "T1195.003", name: "Supply Chain Compromise: Compromise Hardware Supply Chain", tactics: ["Initial Access"] },
  { id: "T1196", name: "Control Panel Items", tactics: [], revokedBy: "T1218.002" },
  { id: "T1197", name: "BITS Jobs", tactics: ["Stealth", "Persistence", "Execution"] },
  { id: "T1198", name: "SIP and Trust Provider Hijacking", tactics: [], revokedBy: "T1553.003" },
  { id: "T1199", name: "Trusted Relationship", tactics: ["Initial Access"] },
  { id: "T1200", name: "Hardware Additions", tactics: ["Initial Access"] },
  { id: "T1201", name: "Password Policy Discovery", tactics: ["Discovery"] },
  { id: "T1202", name: "Indirect Command Execution", tactics: ["Stealth"] },
  { id: "T1203", name: "Exploitation for Client Execution", tactics: ["Execution"] },
  { id: "T1204", name: "User Execution", tactics: ["Execution"] },
  { id: "T1204.001", name: "User Execution: Malicious Link", tactics: ["Execution"] },
  { id: "T1204.002", name: "User Execution: Malicious File", tactics: ["Execution"] },
  { id: "T1204.003", name: "User Execution: Malicious Image", tactics: ["Execution"] },
  { id: "T1204.004", name: "User Execution: Malicious Copy and Paste", tactics: ["Execution"] },
  { id: "T1204.005", name: "User Execution: Malicious Library", tactics: ["Execution"] },
  { id: "T1205", name: "Traffic Signaling", tactics: ["Stealth", "Persistence", "Command and Control"] },
  { id: "T1205.001", name: "Traffic Signaling: Port Knocking", tactics: ["Stealth", "Persistence", "Command and Control"] },
  { id: "T1205.002", name: "Traffic Signaling: Socket Filters", tactics: ["Stealth", "Persistence", "Command and Control"] },
  { id: "T1206", name: "Sudo Caching", tactics: [], revokedBy: "T1548.003" },
  { id: "T1207", name: "Rogue Domain Controller", tactics: ["Defense Impairment"] },
  { id: "T1208", name: "Kerberoasting", tactics: [], revokedBy: "T1558.003" },
  { id: "T1209", name: "Time Providers", tactics: [], revokedBy: "T1547.003" },
  { id: "T1210", name: "Exploitation of Remote Services", tactics: ["Lateral Movement"] },
  { id: "T1211", name: "Exploitation for Stealth", tactics: ["Stealth"] },
  { id: "T1212", name: "Exploitation for Credential Access", tactics: ["Credential Access"] },
  { id: "T1213", name: "Data from Information Repositories", tactics: ["Collection"] },
  { id: "T1213.001", name: "Data from Information Repositories: Confluence", tactics: ["Collection"] },
  { id: "T1213.002", name: "Data from Information Repositories: Sharepoint", tactics: ["Collection"] },
  { id: "T1213.003", name: "Data from Information Repositories: Code Repositories", tactics: ["Collection"] },
  { id: "T1213.004", name: "Data from Information Repositories: Customer Relationship Management Software", tactics: ["Collection"] },
  { id: "T1213.005", name: "Data from Information Repositories: Messaging Applications", tactics: ["Collection"] },
  { id: "T1213.006", name: "Data from Information Repositories: Databases", tactics: ["Collection"] },
  { id: "T1214", name: "Credentials in Registry", tactics: [], revokedBy: "T1552.002" },
  { id: "T1215", name: "Kernel Modules and Extensions", tactics: [], revokedBy: "T1547.006" },
  { id: "T1216", name: "System Script Proxy Execution", tactics: ["Stealth"] },
  { id: "T1216.001", name: "System Script Proxy Execution: PubPrn", tactics: ["Stealth"] },
  { id: "T1216.002", name: "System Script Proxy Execution: SyncAppvPublishingServer", tactics: ["Stealth"] },
  { id: "T1217", name: "Browser Information Discovery", tactics: ["Discovery"] },
  { id: "T1218", name: "System Binary Proxy Execution", tactics: ["Stealth"] },
  { id: "T1218.001", name: "System Binary Proxy Execution: Compiled HTML File", tactics: ["Stealth"] },
  { id: "T1218.002", name: "System Binary Proxy Execution: Control Panel", tactics: ["Stealth"] },
  { id: "T1218.003", name: "System Binary Proxy Execution: CMSTP", tactics: ["Stealth"] },
  { id: "T1218.004", name: "System Binary Proxy Execution: InstallUtil", tactics: ["Stealth"] },
  { id: "T1218.005", name: "System Binary Proxy Execution: Mshta", tactics: ["Stealth"] },
  { id: "T1218.007", name: "System Binary Proxy Execution: Msiexec", tactics: ["Stealth"] },
  { id: "T1218.008", name: "System Binary Proxy Execution: Odbcconf", tactics: ["Stealth"] },
  { id: "T1218.009", name: "System Binary Proxy Execution: Regsvcs/Regasm", tactics: ["Stealth"] },
  { id: "T1218.010", name: "System Binary Proxy Execution: Regsvr32", tactics: ["Stealth"] },
  { id: "T1218.011", name: "System Binary Proxy Execution: Rundll32", tactics: ["Stealth"] },
  { id: "T1218.012", name: "System Binary Proxy Execution: Verclsid", tactics: ["Stealth"] },
  { id: "T1218.013", name: "System Binary Proxy Execution: Mavinject", tactics: ["Stealth"] },
  { id: "T1218.014", name: "System Binary Proxy Execution: MMC", tactics: ["Stealth"] },
  { id: "T1218.015", name: "System Binary Proxy Execution: Electron Applications", tactics: ["Stealth"] },
  { id: "T1219", name: "Remote Access Tools", tactics: ["Command and Control"] },
  { id: "T1219.001", name: "Remote Access Tools: IDE Tunneling", tactics: ["Command and Control"] },
  { id: "T1219.002", name: "Remote Access Tools: Remote Desktop Software", tactics: ["Command and Control"] },
  { id: "T1219.003", name: "Remote Access Tools: Remote Access Hardware", tactics: ["Command and Control"] },
  { id: "T1220", name: "XSL Script Processing", tactics: ["Stealth"] },
  { id: "T1221", name: "Template Injection", tactics: ["Stealth"] },
  { id: "T1222", name: "File and Directory Permissions Modification", tactics: ["Defense Impairment"] },
  { id: "T1222.001", name: "File and Directory Permissions Modification: Windows Permissions", tactics: ["Defense Impairment"] },
  { id: "T1222.002", name: "File and Directory Permissions Modification: Linux and Mac Permissions", tactics: ["Defense Impairment"] },
  { id: "T1223", name: "Compiled HTML File", tactics: [], revokedBy: "T1218.001" },
  { id: "T1480", name: "Execution Guardrails", tactics: ["Stealth"] },
  { id: "T1480.001", name: "Execution Guardrails: Environmental Keying", tactics: ["Stealth"] },
  { id: "T1480.002", name: "Execution Guardrails: Mutual Exclusion", tactics: ["Stealth"] },
  { id: "T1482", name: "Domain Trust Discovery", tactics: ["Discovery"] },
  { id: "T1483", name: "Domain Generation Algorithms", tactics: [], revokedBy: "T1568.002" },
  { id: "T1484", name: "Domain or Tenant Policy Modification", tactics: ["Defense Impairment", "Privilege Escalation"] },
  { id: "T1484.001", name: "Domain or Tenant Policy Modification: Group Policy Modification", tactics: ["Defense Impairment", "Privilege Escalation"] },
  { id: "T1484.002", name: "Domain or Tenant Policy Modification: Trust Modification", tactics: ["Defense Impairment", "Privilege Escalation"] },
  { id: "T1485", name: "Data Destruction", tactics: ["Impact"] },
  { id: "T1485.001", name: "Data Destruction: Lifecycle-Triggered Deletion", tactics: ["Impact"] },
  { id: "T1486", name: "Data Encrypted for Impact", tactics: ["Impact"] },
  { id: "T1487", name: "Disk Structure Wipe", tactics: [], revokedBy: "T1561.002" },
  { id: "T1488", name: "Disk Content Wipe", tactics: [], revokedBy: "T1561.001" },
  { id: "T1489", name: "Service Stop", tactics: ["Impact"] },
  { id: "T1490", name: "Inhibit System Recovery", tactics: ["Impact"] },
  { id: "T1491", name: "Defacement", tactics: ["Impact"] },
  { id: "T1491.001", name: "Defacement: Internal Defacement", tactics: ["Impact"] },
  { id: "T1491.002", name: "Defacement: External Defacement", tactics: ["Impact"] },
  { id: "T1492", name: "Stored Data Manipulation", tactics: [], revokedBy: "T1565.001" },
  { id: "T1493", name: "Transmitted Data Manipulation", tactics: [], revokedBy: "T1565.002" },
  { id: "T1494", name: "Runtime Data Manipulation", tactics: [], revokedBy: "T1565.003" },
  { id: "T1495", name: "Firmware Corruption", tactics: ["Impact"] },
  { id: "T1496", name: "Resource Hijacking", tactics: ["Impact"] },
  { id: "T1496.001", name: "Resource Hijacking: Compute Hijacking", tactics: ["Impact"] },
  { id: "T1496.002", name: "Resource Hijacking: Bandwidth Hijacking", tactics: ["Impact"] },
  { id: "T1496.003", name: "Resource Hijacking: SMS Pumping", tactics: ["Impact"] },
  { id: "T1496.004", name: "Resource Hijacking: Cloud Service Hijacking", tactics: ["Impact"] },
  { id: "T1497", name: "Virtualization/Sandbox Evasion", tactics: ["Stealth", "Discovery"] },
  { id: "T1497.001", name: "Virtualization/Sandbox Evasion: System Checks", tactics: ["Stealth", "Discovery"] },
  { id: "T1497.002", name: "Virtualization/Sandbox Evasion: User Activity Based Checks", tactics: ["Stealth", "Discovery"] },
  { id: "T1497.003", name: "Virtualization/Sandbox Evasion: Time Based Checks", tactics: ["Stealth", "Discovery"] },
  { id: "T1498", name: "Network Denial of Service", tactics: ["Impact"] },
  { id: "T1498.001", name: "Network Denial of Service: Direct Network Flood", tactics: ["Impact"] },
  { id: "T1498.002", name: "Network Denial of Service: Reflection Amplification", tactics: ["Impact"] },
  { id: "T1499", name: "Endpoint Denial of Service", tactics: ["Impact"] },
  { id: "T1499.001", name: "Endpoint Denial of Service: OS Exhaustion Flood", tactics: ["Impact"] },
  { id: "T1499.002", name: "Endpoint Denial of Service: Service Exhaustion Flood", tactics: ["Impact"] },
  { id: "T1499.003", name: "Endpoint Denial of Service: Application Exhaustion Flood", tactics: ["Impact"] },
  { id: "T1499.004", name: "Endpoint Denial of Service: Application or System Exploitation", tactics: ["Impact"] },
  { id: "T1500", name: "Compile After Delivery", tactics: [], revokedBy: "T1027.004" },
  { id: "T1501", name: "Systemd Service", tactics: [], revokedBy: "T1543.002" },
  { id: "T1502", name: "Parent PID Spoofing", tactics: [], revokedBy: "T1134.004" },
  { id: "T1503", name: "Credentials from Web Browsers", tactics: [], revokedBy: "T1555.003" },
  { id: "T1504", name: "PowerShell Profile", tactics: [], revokedBy: "T1546.013" },
  { id: "T1505", name: "Server Software Component", tactics: ["Persistence"] },
  { id: "T1505.001", name: "Server Software Component: SQL Stored Procedures", tactics: ["Persistence"] },
  { id: "T1505.002", name: "Server Software Component: Transport Agent", tactics: ["Persistence"] },
  { id: "T1505.003", name: "Server Software Component: Web Shell", tactics: ["Persistence"] },
  { id: "T1505.004", name: "Server Software Component: IIS Components", tactics: ["Persistence"] },
  { id: "T1505.005", name: "Server Software Component: Terminal Services DLL", tactics: ["Persistence"] },
  { id: "T1505.006", name: "Server Software Component: vSphere Installation Bundles", tactics: ["Persistence"] },
  { id: "T1506", name: "Web Session Cookie", tactics: [], revokedBy: "T1550.004" },
  { id: "T1514", name: "Elevated Execution with Prompt", tactics: [], revokedBy: "T1548.004" },
  { id: "T1518", name: "Software Discovery", tactics: ["Discovery"] },
  { id: "T1518.001", name: "Software Discovery: Security Software Discovery", tactics: ["Discovery"] },
  { id: "T1518.002", name: "Software Discovery: Backup Software Discovery", tactics: ["Discovery"] },
  { id: "T1519", name: "Emond", tactics: [], revokedBy: "T1546.014" },
  { id: "T1522", name: "Cloud Instance Metadata API", tactics: [], revokedBy: "T1552.005" },
  { id: "T1525", name: "Implant Internal Image", tactics: ["Persistence"] },
  { id: "T1526", name: "Cloud Service Discovery", tactics: ["Discovery"] },
  { id: "T1527", name: "Application Access Token", tactics: [], revokedBy: "T1550.001" },
  { id: "T1528", name: "Steal Application Access Token", tactics: ["Credential Access"] },
  { id: "T1529", name: "System Shutdown/Reboot", tactics: ["Impact"] },
  { id: "T1530", name: "Data from Cloud Storage", tactics: ["Collection"] },
  { id: "T1531", name: "Account Access Removal", tactics: ["Impact"] },
  { id: "T1534", name: "Internal Spearphishing", tactics: ["Lateral Movement"] },
  { id: "T1535", name: "Unused/Unsupported Cloud Regions", tactics: ["Stealth"] },
  { id: "T1536", name: "Revert Cloud Instance", tactics: [], revokedBy: "T1578.004" },
  { id: "T1537", name: "Transfer Data to Cloud Account", tactics: ["Exfiltration"] },
  { id: "T1538", name: "Cloud Service Dashboard", tactics: ["Discovery"] },
  { id: "T1539", name: "Steal Web Session Cookie", tactics: ["Credential Access"] },
  { id: "T1542", name: "Pre-OS Boot", tactics: ["Stealth", "Persistence"] },
  { id: "T1542.001", name: "Pre-OS Boot: System Firmware", tactics: ["Stealth", "Persistence"] },
  { id: "T1542.002", name: "Pre-OS Boot: Component Firmware", tactics: ["Stealth", "Persistence"] },
  { id: "T1542.003", name: "Pre-OS Boot: Bootkit", tactics: ["Stealth", "Persistence"] },
  { id: "T1542.004", name: "Pre-OS Boot: ROMMONkit", tactics: ["Stealth", "Persistence"] },
  { id: "T1542.005", name: "Pre-OS Boot: TFTP Boot", tactics: ["Stealth", "Persistence"] },
  { id: "T1543", name: "Create or Modify System Process", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1543.001", name: "Create or Modify System Process: Launch Agent", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1543.002", name: "Create or Modify System Process: Systemd Service", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1543.003", name: "Create or Modify System Process: Windows Service", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1543.004", name: "Create or Modify System Process: Launch Daemon", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1543.005", name: "Create or Modify System Process: Container Service", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1546", name: "Event Triggered Execution", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.001", name: "Event Triggered Execution: Change Default File Association", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.002", name: "Event Triggered Execution: Screensaver", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.003", name: "Event Triggered Execution: Windows Management Instrumentation Event Subscription", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.004", name: "Event Triggered Execution: Unix Shell Configuration Modification", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.005", name: "Event Triggered Execution: Trap", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.006", name: "Event Triggered Execution: LC_LOAD_DYLIB Addition", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.007", name: "Event Triggered Execution: Netsh Helper DLL", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.008", name: "Event Triggered Execution: Accessibility Features", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.009", name: "Event Triggered Execution: AppCert DLLs", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.010", name: "Event Triggered Execution: AppInit DLLs", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.011", name: "Event Triggered Execution: Application Shimming", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.012", name: "Event Triggered Execution: Image File Execution Options Injection", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.013", name: "Event Triggered Execution: PowerShell Profile", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.014", name: "Event Triggered Execution: Emond", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.015", name: "Event Triggered Execution: Component Object Model Hijacking", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.016", name: "Event Triggered Execution: Installer Packages", tactics: ["Privilege Escalation", "Persistence"] },
  { id: "T1546.017", name: "Event Triggered Execution: Udev Rules", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1546.018", name: "Event Triggered Execution: Python Startup Hooks", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547", name: "Boot or Logon Autostart Execution", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.001", name: "Boot or Logon Autostart Execution: Registry Run Keys / Startup Folder", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.002", name: "Boot or Logon Autostart Execution: Authentication Package", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.003", name: "Boot or Logon Autostart Execution: Time Providers", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.004", name: "Boot or Logon Autostart Execution: Winlogon Helper DLL", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.005", name: "Boot or Logon Autostart Execution: Security Support Provider", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.006", name: "Boot or Logon Autostart Execution: Kernel Modules and Extensions", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.007", name: "Boot or Logon Autostart Execution: Re-opened Applications", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.008", name: "Boot or Logon Autostart Execution: LSASS Driver", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.009", name: "Boot or Logon Autostart Execution: Shortcut Modification", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.010", name: "Boot or Logon Autostart Execution: Port Monitors", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.011", name: "Plist Modification", tactics: [], revokedBy: "T1647" },
  { id: "T1547.012", name: "Boot or Logon Autostart Execution: Print Processors", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.013", name: "Boot or Logon Autostart Execution: XDG Autostart Entries", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.014", name: "Boot or Logon Autostart Execution: Active Setup", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1547.015", name: "Boot or Logon Autostart Execution: Login Items", tactics: ["Persistence", "Privilege Escalation"] },
  { id: "T1548", name: "Abuse Elevation Control Mechanism", tactics: ["Privilege Escalation"] },
  { id: "T1548.001", name: "Abuse Elevation Control Mechanism: Setuid and Setgid", tactics: ["Privilege Escalation"] },
  { id: "T1548.002", name: "Abuse Elevation Control Mechanism: Bypass User Account Control", tactics: ["Privilege Escalation"] },
  { id: "T1548.003", name: "Abuse Elevation Control Mechanism: Sudo and Sudo Caching", tactics: ["Privilege Escalation"] },
  { id: "T1548.004", name: "Abuse Elevation Control Mechanism: Elevated Execution with Prompt", tactics: ["Privilege Escalation"] },
  { id: "T1548.005", name: "Abuse Elevation Control Mechanism: Temporary Elevated Cloud Access", tactics: ["Privilege Escalation"] },
  { id: "T1548.006", name: "Abuse Elevation Control Mechanism: TCC Manipulation", tactics: ["Privilege Escalation"] },
  { id: "T1550", name: "Use Alternate Authentication Material", tactics: ["Lateral Movement"] },
  { id: "T1550.001", name: "Use Alternate Authentication Material: Application Access Token", tactics: ["Lateral Movement"] },
  { id: "T1550.002", name: "Use Alternate Authentication Material: Pass the Hash", tactics: ["Lateral Movement"] },
  { id: "T1550.003", name: "Use Alternate Authentication Material: Pass the Ticket", tactics: ["Lateral Movement"] },
  { id: "T1550.004", name: "Use Alternate Authentication Material: Web Session Cookie", tactics: ["Lateral Movement"] },
  { id: "T1552", name: "Unsecured Credentials", tactics: ["Credential Access"] },
  { id: "T1552.001", name: "Unsecured Credentials: Credentials In Files", tactics: ["Credential Access"] },
  { id: "T1552.002", name: "Unsecured Credentials: Credentials in Registry", tactics: ["Credential Access"] },
  { id: "T1552.003", name: "Unsecured Credentials: Shell History", tactics: ["Credential Access"] },
  { id: "T1552.004", name: "Unsecured Credentials: Private Keys", tactics: ["Credential Access"] },
  { id: "T1552.005", name: "Unsecured Credentials: Cloud Instance Metadata API", tactics: ["Credential Access"] },
  { id: "T1552.006", name: "Unsecured Credentials: Group Policy Preferences", tactics: ["Credential Access"] },
  { id: "T1552.007", name: "Unsecured Credentials: Container API", tactics: ["Credential Access"] },
  { id: "T1552.008", name: "Unsecured Credentials: Chat Messages", tactics: ["Credential Access"] },
  { id: "T1553", name: "Subvert Trust Controls", tactics: ["Defense Impairment"] },
  { id: "T1553.001", name: "Subvert Trust Controls: Gatekeeper Bypass", tactics: ["Defense Impairment"] },
  { id: "T1553.002", name: "Subvert Trust Controls: Code Signing", tactics: ["Defense Impairment"] },
  { id: "T1553.003", name: "Subvert Trust Controls: SIP and Trust Provider Hijacking", tactics: ["Defense Impairment"] },
  { id: "T1553.004", name: "Subvert Trust Controls: Install Root Certificate", tactics: ["Defense Impairment"] },
  { id: "T1553.005", name: "Subvert Trust Controls: Mark-of-the-Web Bypass", tactics: ["Defense Impairment"] },
  { id: "T1553.006", name: "Subvert Trust Controls: Code Signing Policy Modification", tactics: ["Defense Impairment"] },
  { id: "T1554", name: "Compromise Host Software Binary", tactics: ["Persistence"] },
  { id: "T1555", name: "Credentials from Password Stores", tactics: ["Credential Access"] },
  { id: "T1555.001", name: "Credentials from Password Stores: Keychain", tactics: ["Credential Access"] },
  { id: "T1555.002", name: "Credentials from Password Stores: Securityd Memory", tactics: ["Credential Access"] },
  { id: "T1555.003", name: "Credentials from Password Stores: Credentials from Web Browsers", tactics: ["Credential Access"] },
  { id: "T1555.004", name: "Credentials from Password Stores: Windows Credential Manager", tactics: ["Credential Access"] },
  { id: "T1555.005", name: "Credentials from Password Stores: Password Managers", tactics: ["Credential Access"] },
  { id: "T1555.006", name: "Credentials from Password Stores: Cloud Secrets Management Stores", tactics: ["Credential Access"] },
  { id: "T1556", name: "Modify Authentication Process", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.001", name: "Modify Authentication Process: Domain Controller Authentication", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.002", name: "Modify Authentication Process: Password Filter DLL", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.003", name: "Modify Authentication Process: Pluggable Authentication Modules", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.004", name: "Modify Authentication Process: Network Device Authentication", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.005", name: "Modify Authentication Process: Reversible Encryption", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.006", name: "Modify Authentication Process: Multi-Factor Authentication", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.007", name: "Modify Authentication Process: Hybrid Identity", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.008", name: "Modify Authentication Process: Network Provider DLL", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1556.009", name: "Modify Authentication Process: Conditional Access Policies", tactics: ["Defense Impairment", "Persistence", "Credential Access"] },
  { id: "T1557", name: "Adversary-in-the-Middle", tactics: ["Credential Access", "Collection"] },
  { id: "T1557.001", name: "Adversary-in-the-Middle: Name Resolution Poisoning and SMB Relay", tactics: ["Credential Access", "Collection"] },
  { id: "T1557.002", name: "Adversary-in-the-Middle: ARP Cache Poisoning", tactics: ["Credential Access", "Collection"] },
  { id: "T1557.003", name: "Adversary-in-the-Middle: DHCP Spoofing", tactics: ["Credential Access", "Collection"] },
  { id: "T1557.004", name: "Adversary-in-the-Middle: Evil Twin", tactics: ["Credential Access", "Collection"] },
  { id: "T1558", name: "Steal or Forge Kerberos Tickets", tactics: ["Credential Access"] },
  { id: "T1558.001", name: "Steal or Forge Kerberos Tickets: Golden Ticket", tactics: ["Credential Access"] },
  { id: "T1558.002", name: "Steal or Forge Kerberos Tickets: Silver Ticket", tactics: ["Credential Access"] },
  { id: "T1558.003", name: "Steal or Forge Kerberos Tickets: Kerberoasting", tactics: ["Credential Access"] },
  { id: "T1558.004", name: "Steal or Forge Kerberos Tickets: AS-REP Roasting", tactics: ["Credential Access"] },
  { id: "T1558.005", name: "Steal or Forge Kerberos Tickets: Ccache Files", tactics: ["Credential Access"] },
  { id: "T1559", name: "Inter-Process Communication", tactics: ["Execution"] },
  { id: "T1559.001", name: "Inter-Process Communication: Component Object Model", tactics: ["Execution"] },
  { id: "T1559.002", name: "Inter-Process Communication: Dynamic Data Exchange", tactics: ["Execution"] },
  { id: "T1559.003", name: "Inter-Process Communication: XPC Services", tactics: ["Execution"] },
  { id: "T1560", name: "Archive Collected Data", tactics: ["Collection"] },
  { id: "T1560.001", name: "Archive Collected Data: Archive via Utility", tactics: ["Collection"] },
  { id: "T1560.002", name: "Archive Collected Data: Archive via Library", tactics: ["Collection"] },
  { id: "T1560.003", name: "Archive Collected Data: Archive via Custom Method", tactics: ["Collection"] },
  { id: "T1561", name: "Disk Wipe", tactics: ["Impact"] },
  { id: "T1561.001", name: "Disk Wipe: Disk Content Wipe", tactics: ["Impact"] },
  { id: "T1561.002", name: "Disk Wipe: Disk Structure Wipe", tactics: ["Impact"] },
  { id: "T1562", name: "Impair Defenses", tactics: [], revokedBy: "T1685" },
  { id: "T1562.001", name: "Disable or Modify Tools", tactics: [], revokedBy: "T1685" },
  { id: "T1562.002", name: "Disable Windows Event Logging", tactics: [], revokedBy: "T1685.001" },
  { id: "T1562.003", name: "Impair Command History Logging", tactics: [], revokedBy: "T1690" },
  { id: "T1562.004", name: "Disable or Modify System Firewall", tactics: [], revokedBy: "T1686" },
  { id: "T1562.006", name: "Indicator Blocking", tactics: [], revokedBy: "T1685" },
  { id: "T1562.007", name: "Disable or Modify Cloud Firewall", tactics: [], revokedBy: "T1686.001" },
  { id: "T1562.008", name: "Disable or Modify Cloud Logs", tactics: [], revokedBy: "T1685.002" },
  { id: "T1562.009", name: "Safe Mode Boot", tactics: [], revokedBy: "T1688" },
  { id: "T1562.010", name: "Downgrade Attack", tactics: [], revokedBy: "T1689" },
  { id: "T1562.011", name: "Spoof Security Alerting", tactics: [], revokedBy: "T1685.003" },
  { id: "T1562.012", name: "Disable or Modify Linux Audit System", tactics: [], revokedBy: "T1685.004" },
  { id: "T1562.013", name: "Disable or Modify Network Device Firewall", tactics: [], revokedBy: "T1686.002" },
  { id: "T1563", name: "Remote Service Session Hijacking", tactics: ["Lateral Movement"] },
  { id: "T1563.001", name: "Remote Service Session Hijacking: SSH Hijacking", tactics: ["Lateral Movement"] },
  { id: "T1563.002", name: "Remote Service Session Hijacking: RDP Hijacking", tactics: ["Lateral Movement"] },
  { id: "T1564", name: "Hide Artifacts", tactics: ["Stealth"] },
  { id: "T1564.001", name: "Hide Artifacts: Hidden Files and Directories", tactics: ["Stealth"] },
  { id: "T1564.002", name: "Hide Artifacts: Hidden Users", tactics: ["Stealth"] },
  { id: "T1564.003", name: "Hide Artifacts: Hidden Window", tactics: ["Stealth"] },
  { id: "T1564.004", name: "Hide Artifacts: NTFS File Attributes", tactics: ["Stealth"] },
  { id: "T1564.005", name: "Hide Artifacts: Hidden File System", tactics: ["Stealth"] },
  { id: "T1564.006", name: "Hide Artifacts: Run Virtual Instance", tactics: ["Stealth"] },
  { id: "T1564.007", name: "Hide Artifacts: VBA Stomping", tactics: ["Stealth"] },
  { id: "T1564.008", name: "Hide Artifacts: Email Hiding Rules", tactics: ["Stealth"] },
  { id: "T1564.009", name: "Hide Artifacts: Resource Forking", tactics: ["Stealth"] },
  { id: "T1564.010", name: "Hide Artifacts: Process Argument Spoofing", tactics: ["Stealth"] },
  { id: "T1564.011", name: "Hide Artifacts: Ignore Process Interrupts", tactics: ["Stealth"] },
  { id: "T1564.012", name: "Hide Artifacts: File/Path Exclusions", tactics: ["Stealth"] },
  { id: "T1564.013", name: "Hide Artifacts: Bind Mounts", tactics: ["Stealth"] },
  { id: "T1564.014", name: "Hide Artifacts: Extended Attributes", tactics: ["Stealth"] },
  { id: "T1565", name: "Data Manipulation", tactics: ["Impact"] },
  { id: "T1565.001", name: "Data Manipulation: Stored Data Manipulation", tactics: ["Impact"] },
  { id: "T1565.002", name: "Data Manipulation: Transmitted Data Manipulation", tactics: ["Impact"] },
  { id: "T1565.003", name: "Data Manipulation: Runtime Data Manipulation", tactics: ["Impact"] },
  { id: "T1566", name: "Phishing", tactics: ["Initial Access"] },
  { id: "T1566.001", name: "Phishing: Spearphishing Attachment", tactics: ["Initial Access"] },
  { id: "T1566.002", name: "Phishing: Spearphishing Link", tactics: ["Initial Access"] },
  { id: "T1566.003", name: "Phishing: Spearphishing via Service", tactics: ["Initial Access"] },
  { id: "T1566.004", name: "Phishing: Spearphishing Voice", tactics: ["Initial Access"] },
  { id: "T1567", name: "Exfiltration Over Web Service", tactics: ["Exfiltration"] },
  { id: "T1567.001", name: "Exfiltration Over Web Service: Exfiltration to Code Repository", tactics: ["Exfiltration"] },
  { id: "T1567.002", name: "Exfiltration Over Web Service: Exfiltration to Cloud Storage", tactics: ["Exfiltration"] },
  { id: "T1567.003", name: "Exfiltration Over Web Service: Exfiltration to Text Storage Sites", tactics: ["Exfiltration"] },
  { id: "T1567.004", name: "Exfiltration Over Web Service: Exfiltration Over Webhook", tactics: ["Exfiltration"] },
  { id: "T1568", name: "Dynamic Resolution", tactics: ["Command and Control"] },
  { id: "T1568.001", name: "Dynamic Resolution: Fast Flux DNS", tactics: ["Command and Control"] },
  { id: "T1568.002", name: "Dynamic Resolution: Domain Generation Algorithms", tactics: ["Command and Control"] },
  { id: "T1568.003", name: "Dynamic Resolution: DNS Calculation", tactics: ["Command and Control"] },
  { id: "T1569", name: "System Services", tactics: ["Execution"] },
  { id: "T1569.001", name: "System Services: Launchctl", tactics: ["Execution"] },
  { id: "T1569.002", name: "System Services: Service Execution", tactics: ["Execution"] },
  { id: "T1569.003", name: "System Services: Systemctl", tactics: ["Execution"] },
  { id: "T1570", name: "Lateral Tool Transfer", tactics: ["Lateral Movement"] },
  { id: "T1571", name: "Non-Standard Port", tactics: ["Command and Control"] },
  { id: "T1572", name: "Protocol Tunneling", tactics: ["Command and Control"] },
  { id: "T1573", name: "Encrypted Channel", tactics: ["Command and Control"] },
  { id: "T1573.001", name: "Encrypted Channel: Symmetric Cryptography", tactics: ["Command and Control"] },
  { id: "T1573.002", name: "Encrypted Channel: Asymmetric Cryptography", tactics: ["Command and Control"] },
  { id: "T1574", name: "Hijack Execution Flow", tactics: ["Stealth", "Execution"] },
  { id: "T1574.001", name: "Hijack Execution Flow: DLL", tactics: ["Stealth", "Execution"] },
  { id: "T1574.002", name: "DLL Side-Loading", tactics: [], revokedBy: "T1574.001" },
  { id: "T1574.004", name: "Hijack Execution Flow: Dylib Hijacking", tactics: ["Stealth", "Execution"] },
  { id: "T1574.005", name: "Hijack Execution Flow: Executable Installer File Permissions Weakness", tactics: ["Stealth", "Execution"] },
  { id: "T1574.006", name: "Hijack Execution Flow: Dynamic Linker Hijacking", tactics: ["Stealth", "Execution"] },
  { id: "T1574.007", name: "Hijack Execution Flow: Path Interception by PATH Environment Variable", tactics: ["Stealth", "Execution"] },
  { id: "T1574.008", name: "Hijack Execution Flow: Path Interception by Search Order Hijacking", tactics: ["Stealth", "Execution"] },
  { id: "T1574.009", name: "Hijack Execution Flow: Path Interception by Unquoted Path", tactics: ["Stealth", "Execution"] },
  { id: "T1574.010", name: "Hijack Execution Flow: Services File Permissions Weakness", tactics: ["Stealth", "Execution"] },
  { id: "T1574.011", name: "Hijack Execution Flow: Services Registry Permissions Weakness", tactics: ["Stealth", "Execution"] },
  { id: "T1574.012", name: "Hijack Execution Flow: COR_PROFILER", tactics: ["Stealth", "Execution"] },
  { id: "T1574.013", name: "Hijack Execution Flow: KernelCallbackTable", tactics: ["Stealth", "Execution"] },
  { id: "T1574.014", name: "Hijack Execution Flow: AppDomainManager", tactics: ["Stealth", "Execution"] },
  { id: "T1578", name: "Modify Cloud Compute Infrastructure", tactics: ["Defense Impairment"] },
  { id: "T1578.001", name: "Modify Cloud Compute Infrastructure: Create Snapshot", tactics: ["Defense Impairment"] },
  { id: "T1578.002", name: "Modify Cloud Compute Infrastructure: Create Cloud Instance", tactics: ["Defense Impairment"] },
  { id: "T1578.003", name: "Modify Cloud Compute Infrastructure: Delete Cloud Instance", tactics: ["Defense Impairment"] },
  { id: "T1578.004", name: "Modify Cloud Compute Infrastructure: Revert Cloud Instance", tactics: ["Defense Impairment"] },
  { id: "T1578.005", name: "Modify Cloud Compute Infrastructure: Modify Cloud Compute Configurations", tactics: ["Defense Impairment"] },
  { id: "T1580", name: "Cloud Infrastructure Discovery", tactics: ["Discovery"] },
  { id: "T1583", name: "Acquire Infrastructure", tactics: ["Resource Development"] },
  { id: "T1583.001", name: "Acquire Infrastructure: Domains", tactics: ["Resource Development"] },
  { id: "T1583.002", name: "Acquire Infrastructure: DNS Server", tactics: ["Resource Development"] },
  { id: "T1583.003", name: "Acquire Infrastructure: Virtual Private Server", tactics: ["Resource Development"] },
  { id: "T1583.004", name: "Acquire Infrastructure: Server", tactics: ["Resource Development"] },
  { id: "T1583.005", name: "Acquire Infrastructure: Botnet", tactics: ["Resource Development"] },
  { id: "T1583.006", name: "Acquire Infrastructure: Web Services", tactics: ["Resource Development"] },
  { id: "T1583.007", name: "Acquire Infrastructure: Serverless", tactics: ["Resource Development"] },
  { id: "T1583.008", name: "Acquire Infrastructure: Malvertising", tactics: ["Resource Development"] },
  { id: "T1584", name: "Compromise Infrastructure", tactics: ["Resource Development"] },
  { id: "T1584.001", name: "Compromise Infrastructure: Domains", tactics: ["Resource Development"] },
  { id: "T1584.002", name: "Compromise Infrastructure: DNS Server", tactics: ["Resource Development"] },
  { id: "T1584.003", name: "Compromise Infrastructure: Virtual Private Server", tactics: ["Resource Development"] },
  { id: "T1584.004", name: "Compromise Infrastructure: Server", tactics: ["Resource Development"] },
  { id: "T1584.005", name: "Compromise Infrastructure: Botnet", tactics: ["Resource Development"] },
  { id: "T1584.006", name: "Compromise Infrastructure: Web Services", tactics: ["Resource Development"] },
  { id: "T1584.007", name: "Compromise Infrastructure: Serverless", tactics: ["Resource Development"] },
  { id: "T1584.008", name: "Compromise Infrastructure: Network Devices", tactics: ["Resource Development"] },
  { id: "T1585", name: "Establish Accounts", tactics: ["Resource Development"] },
  { id: "T1585.001", name: "Establish Accounts: Social Media Accounts", tactics: ["Resource Development"] },
  { id: "T1585.002", name: "Establish Accounts: Email Accounts", tactics: ["Resource Development"] },
  { id: "T1585.003", name: "Establish Accounts: Cloud Accounts", tactics: ["Resource Development"] },
  { id: "T1586", name: "Compromise Accounts", tactics: ["Resource Development"] },
  { id: "T1586.001", name: "Compromise Accounts: Social Media Accounts", tactics: ["Resource Development"] },
  { id: "T1586.002", name: "Compromise Accounts: Email Accounts", tactics: ["Resource Development"] },
  { id: "T1586.003", name: "Compromise Accounts: Cloud Accounts", tactics: ["Resource Development"] },
  { id: "T1587", name: "Develop Capabilities", tactics: ["Resource Development"] },
  { id: "T1587.001", name: "Develop Capabilities: Malware", tactics: ["Resource Development"] },
  { id: "T1587.002", name: "Develop Capabilities: Code Signing Certificates", tactics: ["Resource Development"] },
  { id: "T1587.003", name: "Develop Capabilities: Digital Certificates", tactics: ["Resource Development"] },
  { id: "T1587.004", name: "Develop Capabilities: Exploits", tactics: ["Resource Development"] },
  { id: "T1588", name: "Obtain Capabilities", tactics: ["Resource Development"] },
  { id: "T1588.001", name: "Obtain Capabilities: Malware", tactics: ["Resource Development"] },
  { id: "T1588.002", name: "Obtain Capabilities: Tool", tactics: ["Resource Development"] },
  { id: "T1588.003", name: "Obtain Capabilities: Code Signing Certificates", tactics: ["Resource Development"] },
  { id: "T1588.004", name: "Obtain Capabilities: Digital Certificates", tactics: ["Resource Development"] },
  { id: "T1588.005", name: "Obtain Capabilities: Exploits", tactics: ["Resource Development"] },
  { id: "T1588.006", name: "Obtain Capabilities: Vulnerabilities", tactics: ["Resource Development"] },
  { id: "T1588.007", name: "Obtain Capabilities: Artificial Intelligence", tactics: ["Resource Development"] },
  { id: "T1589", name: "Gather Victim Identity Information", tactics: ["Reconnaissance"] },
  { id: "T1589.001", name: "Gather Victim Identity Information: Credentials", tactics: ["Reconnaissance"] },
  { id: "T1589.002", name: "Gather Victim Identity Information: Email Addresses", tactics: ["Reconnaissance"] },
  { id: "T1589.003", name: "Gather Victim Identity Information: Employee Names", tactics: ["Reconnaissance"] },
  { id: "T1590", name: "Gather Victim Network Information", tactics: ["Reconnaissance"] },
  { id: "T1590.001", name: "Gather Victim Network Information: Domain Properties", tactics: ["Reconnaissance"] },
  { id: "T1590.002", name: "Gather Victim Network Information: DNS", tactics: ["Reconnaissance"] },
  { id: "T1590.003", name: "Gather Victim Network Information: Network Trust Dependencies", tactics: ["Reconnaissance"] },
  { id: "T1590.004", name: "Gather Victim Network Information: Network Topology", tactics: ["Reconnaissance"] },
  { id: "T1590.005", name: "Gather Victim Network Information: IP Addresses", tactics: ["Reconnaissance"] },
  { id: "T1590.006", name: "Gather Victim Network Information: Network Security Appliances", tactics: ["Reconnaissance"] },
  { id: "T1591", name: "Gather Victim Org Information", tactics: ["Reconnaissance"] },
  { id: "T1591.001", name: "Gather Victim Org Information: Determine Physical Locations", tactics: ["Reconnaissance"] },
  { id: "T1591.002", name: "Gather Victim Org Information: Business Relationships", tactics: ["Reconnaissance"] },
  { id: "T1591.003", name: "Gather Victim Org Information: Identify Business Tempo", tactics: ["Reconnaissance"] },
  { id: "T1591.004", name: "Gather Victim Org Information: Identify Roles", tactics: ["Reconnaissance"] },
  { id: "T1592", name: "Gather Victim Host Information", tactics: ["Reconnaissance"] },
  { id: "T1592.001", name: "Gather Victim Host Information: Hardware", tactics: ["Reconnaissance"] },
  { id: "T1592.002", name: "Gather Victim Host Information: Software", tactics: ["Reconnaissance"] },
  { id: "T1592.003", name: "Gather Victim Host Information: Firmware", tactics: ["Reconnaissance"] },
  { id: "T1592.004", name: "Gather Victim Host Information: Client Configurations", tactics: ["Reconnaissance"] },
  { id: "T1593", name: "Search Open Websites/Domains", tactics: ["Reconnaissance"] },
  { id: "T1593.001", name: "Search Open Websites/Domains: Social Media", tactics: ["Reconnaissance"] },
  { id: "T1593.002", name: "Search Open Websites/Domains: Search Engines", tactics: ["Reconnaissance"] },
  { id: "T1593.003", name: "Search Open Websites/Domains: Code Repositories", tactics: ["Reconnaissance"] },
  { id: "T1594", name: "Search Victim-Owned Websites", tactics: ["Reconnaissance"] },
  { id: "T1595", name: "Active Scanning", tactics: ["Reconnaissance"] },
  { id: "T1595.001", name: "Active Scanning: Scanning IP Blocks", tactics: ["Reconnaissance"] },
  { id: "T1595.002", name: "Active Scanning: Vulnerability Scanning", tactics: ["Reconnaissance"] },
  { id: "T1595.003", name: "Active Scanning: Wordlist Scanning", tactics: ["Reconnaissance"] },
  { id: "T1596", name: "Search Open Technical Databases", tactics: ["Reconnaissance"] },
  { id: "T1596.001", name: "Search Open Technical Databases: DNS/Passive DNS", tactics: ["Reconnaissance"] },
  { id: "T1596.002", name: "Search Open Technical Databases: WHOIS", tactics: ["Reconnaissance"] },
  { id: "T1596.003", name: "Search Open Technical Databases: Digital Certificates", tactics: ["Reconnaissance"] },
  { id: "T1596.004", name: "Search Open Technical Databases: CDNs", tactics: ["Reconnaissance"] },
  { id: "T1596.005", name: "Search Open Technical Databases: Scan Databases", tactics: ["Reconnaissance"] },
  { id: "T1597", name: "Search Closed Sources", tactics: ["Reconnaissance"] },
  { id: "T1597.001", name: "Search Closed Sources: Threat Intel Vendors", tactics: ["Reconnaissance"] },
  { id: "T1597.002", name: "Search Closed Sources: Purchase Technical Data", tactics: ["Reconnaissance"] },
  { id: "T1598", name: "Phishing for Information", tactics: ["Reconnaissance"] },
  { id: "T1598.001", name: "Phishing for Information: Spearphishing Service", tactics: ["Reconnaissance"] },
  { id: "T1598.002", name: "Phishing for Information: Spearphishing Attachment", tactics: ["Reconnaissance"] },
  { id: "T1598.003", name: "Phishing for Information: Spearphishing Link", tactics: ["Reconnaissance"] },
  { id: "T1598.004", name: "Phishing for Information: Spearphishing Voice", tactics: ["Reconnaissance"] },
  { id: "T1599", name: "Network Boundary Bridging", tactics: ["Defense Impairment"] },
  { id: "T1599.001", name: "Network Boundary Bridging: Network Address Translation Traversal", tactics: ["Defense Impairment"] },
  { id: "T1600", name: "Weaken Encryption", tactics: ["Defense Impairment"] },
  { id: "T1600.001", name: "Weaken Encryption: Reduce Key Space", tactics: ["Defense Impairment"] },
  { id: "T1600.002", name: "Weaken Encryption: Disable Crypto Hardware", tactics: ["Defense Impairment"] },
  { id: "T1601", name: "Modify System Image", tactics: ["Defense Impairment"] },
  { id: "T1601.001", name: "Modify System Image: Patch System Image", tactics: ["Defense Impairment"] },
  { id: "T1601.002", name: "Modify System Image: Downgrade System Image", tactics: ["Defense Impairment"] },
  { id: "T1602", name: "Data from Configuration Repository", tactics: ["Collection"] },
  { id: "T1602.001", name: "Data from Configuration Repository: SNMP (MIB Dump)", tactics: ["Collection"] },
  { id: "T1602.002", name: "Data from Configuration Repository: Network Device Configuration Dump", tactics: ["Collection"] },
  { id: "T1606", name: "Forge Web Credentials", tactics: ["Credential Access"] },
  { id: "T1606.001", name: "Forge Web Credentials: Web Cookies", tactics: ["Credential Access"] },
  { id: "T1606.002", name: "Forge Web Credentials: SAML Tokens", tactics: ["Credential Access"] },
  { id: "T1608", name: "Stage Capabilities", tactics: ["Resource Development"] },
  { id: "T1608.001", name: "Stage Capabilities: Upload Malware", tactics: ["Resource Development"] },
  { id: "T1608.002", name: "Stage Capabilities: Upload Tool", tactics: ["Resource Development"] },
  { id: "T1608.003", name: "Stage Capabilities: Install Digital Certificate", tactics: ["Resource Development"] },
  { id: "T1608.004", name: "Stage Capabilities: Drive-by Target", tactics: ["Resource Development"] },
  { id: "T1608.005", name: "Stage Capabilities: Link Target", tactics: ["Resource Development"] },
  { id: "T1608.006", name: "Stage Capabilities: SEO Poisoning", tactics: ["Resource Development"] },
  { id: "T1609", name: "Container Administration Command", tactics: ["Execution"] },
  { id: "T1610", name: "Deploy Container", tactics: ["Execution"] },
  { id: "T1611", name: "Escape to Host", tactics: ["Privilege Escalation"] },
  { id: "T1612", name: "Build Image on Host", tactics: ["Stealth"] },
  { id: "T1613", name: "Container and Resource Discovery", tactics: ["Discovery"] },
  { id: "T1614", name: "System Location Discovery", tactics: ["Discovery"] },
  { id: "T1614.001", name: "System Location Discovery: System Language Discovery", tactics: ["Discovery"] },
  { id: "T1615", name: "Group Policy Discovery", tactics: ["Discovery"] },
  { id: "T1619", name: "Cloud Storage Object Discovery", tactics: ["Discovery"] },
  { id: "T1620", name: "Reflective Code Loading", tactics: ["Stealth"] },
  { id: "T1621", name: "Multi-Factor Authentication Request Generation", tactics: ["Credential Access"] },
  { id: "T1622", name: "Debugger Evasion", tactics: ["Stealth", "Discovery"] },
  { id: "T1647", name: "Plist File Modification", tactics: ["Defense Impairment"] },
  { id: "T1648", name: "Serverless Execution", tactics: ["Execution"] },
  { id: "T1649", name: "Steal or Forge Authentication Certificates", tactics: ["Credential Access"] },
  { id: "T1650", name: "Acquire Access", tactics: ["Resource Development"] },
  { id: "T1651", name: "Cloud Administration Command", tactics: ["Execution"] },
  { id: "T1652", name: "Device Driver Discovery", tactics: ["Discovery"] },
  { id: "T1653", name: "Power Settings", tactics: ["Persistence"] },
  { id: "T1654", name: "Log Enumeration", tactics: ["Discovery"] },
  { id: "T1656", name: "Impersonation", tactics: [], revokedBy: "T1684.001" },
  { id: "T1657", name: "Financial Theft", tactics: ["Impact"] },
  { id: "T1659", name: "Content Injection", tactics: ["Initial Access", "Command and Control"] },
  { id: "T1665", name: "Hide Infrastructure", tactics: ["Command and Control"] },
  { id: "T1666", name: "Modify Cloud Resource Hierarchy", tactics: ["Defense Impairment"] },
  { id: "T1667", name: "Email Bombing", tactics: ["Impact"] },
  { id: "T1668", name: "Exclusive Control", tactics: ["Persistence"] },
  { id: "T1669", name: "Wi-Fi Networks", tactics: ["Initial Access"] },
  { id: "T1671", name: "Cloud Application Integration", tactics: ["Persistence"] },
  { id: "T1672", name: "Email Spoofing", tactics: [], revokedBy: "T1684.002" },
  { id: "T1673", name: "Virtual Machine Discovery", tactics: ["Discovery"] },
  { id: "T1674", name: "Input Injection", tactics: ["Execution"] },
  { id: "T1675", name: "ESXi Administration Command", tactics: ["Execution"] },
  { id: "T1677", name: "Poisoned Pipeline Execution", tactics: ["Execution"] },
  { id: "T1678", name: "Delay Execution", tactics: ["Stealth"] },
  { id: "T1679", name: "Selective Exclusion", tactics: ["Stealth"] },
  { id: "T1680", name: "Local Storage Discovery", tactics: ["Discovery"] },
  { id: "T1681", name: "Search Threat Vendor Data", tactics: ["Reconnaissance"] },
  { id: "T1682", name: "Query Public AI Services", tactics: ["Reconnaissance"] },
  { id: "T1683", name: "Generate Content", tactics: ["Resource Development"] },
  { id: "T1683.001", name: "Generate Content: Written Content", tactics: ["Resource Development"] },
  { id: "T1683.002", name: "Generate Content: Audio-Visual Content", tactics: ["Resource Development"] },
  { id: "T1684", name: "Social Engineering", tactics: ["Stealth"] },
  { id: "T1684.001", name: "Social Engineering: Impersonation", tactics: ["Stealth"] },
  { id: "T1684.002", name: "Social Engineering: Email Spoofing", tactics: ["Stealth"] },
  { id: "T1685", name: "Disable or Modify Tools", tactics: ["Defense Impairment"] },
  { id: "T1685.001", name: "Disable or Modify Tools: Disable or Modify Windows Event Log", tactics: ["Defense Impairment"] },
  { id: "T1685.002", name: "Disable or Modify Tools: Disable or Modify Cloud Log", tactics: ["Defense Impairment"] },
  { id: "T1685.003", name: "Disable or Modify Tools: Modify or Spoof Tool UI", tactics: ["Defense Impairment"] },
  { id: "T1685.004", name: "Disable or Modify Tools: Disable or Modify Linux Audit System Log", tactics: ["Defense Impairment"] },
  { id: "T1685.005", name: "Disable or Modify Tools: Clear Windows Event Logs", tactics: ["Defense Impairment"] },
  { id: "T1685.006", name: "Disable or Modify Tools: Clear Linux or Mac System Logs", tactics: ["Defense Impairment"] },
  { id: "T1686", name: "Disable or Modify System Firewall", tactics: ["Defense Impairment"] },
  { id: "T1686.001", name: "Disable or Modify System Firewall: Cloud Firewall", tactics: ["Defense Impairment"] },
  { id: "T1686.002", name: "Disable or Modify System Firewall: Network Device Firewall", tactics: ["Defense Impairment"] },
  { id: "T1686.003", name: "Disable or Modify System Firewall: Windows Host Firewall", tactics: ["Defense Impairment"] },
  { id: "T1687", name: "Exploitation for Defense Impairment", tactics: ["Defense Impairment"] },
  { id: "T1688", name: "Safe Mode Boot", tactics: ["Defense Impairment"] },
  { id: "T1689", name: "Downgrade Attack", tactics: ["Defense Impairment"] },
  { id: "T1690", name: "Prevent Command History Logging", tactics: ["Defense Impairment"] },
];

const BY_ID = new Map(MITRE_TECHNIQUES.map((t) => [t.id, t]));
export const techniqueById = (id: string): Technique | undefined => BY_ID.get(id);
/** The live technique behind an id: itself, or what a revoked one was replaced by. */
export function currentTechnique(id: string): Technique | undefined {
  let t = BY_ID.get(id);
  for (let n = 0; t?.revokedBy && n < 10; n++) t = BY_ID.get(t.revokedBy);
  return t;
}

/** Datalist label / stored value, e.g. "T1566 Phishing". */
export const techniqueLabel = (t: Technique): string => `${t.id} ${t.name}`;

/** The technique id written at the front of a stored value ("T1566.001 Phishing: …"). */
export const techniqueIdOf = (v: unknown): string | null =>
  typeof v === "string" ? (v.toUpperCase().match(/T\d{4}(?:\.\d{3})?/)?.[0] ?? null) : null;

/** Techniques for the typeahead - all, or those of one tactic. A retired tactic offers
 *  the union of its successors, so an old step still gets suggestions. */
export function suggestTechniques(tactic?: string): readonly Technique[] {
  if (!tactic) return MITRE_TECHNIQUES.filter((t) => !t.revokedBy);
  const names = RETIRED_TACTICS[tactic] ?? [tactic];
  const inTactic = MITRE_TECHNIQUES.filter((t) => t.tactics.some((x) => names.includes(x)));
  return inTactic.length ? inTactic : MITRE_TECHNIQUES.filter((t) => !t.revokedBy);
}
