// SPDX-License-Identifier: MPL-2.0 · Copyright (c) Aurelian-Risk
// The engine's own words, per language.
//
// Text that belongs to THIS layer and not to any product: the completeness checks, the
// buttons, the dialogs, the messages. It looks like product text on screen, which is why
// it needs saying: `lint.ts` declares its checks with an English title and hint, and they
// describe the engine's own modelling. A product that does not switch them off gets them
// unasked.
//
// Without this file each product would translate the same strings into its own table,
// drifting apart the moment one of them fixes a typo - and under the lookup rule a wrong
// translation does not fail, it simply shows.
//
// Registered BEFORE a product's own table, so a product can still override any key it
// disagrees with. It does not decide which languages are on offer - that stays with the
// product, which knows what it ships.
//
// The keys are `ui.<area>.<slug of the authored text>`, written by scripts/keyify.py. The
// other product on this engine keyed its own tree and wrote German for what it found; where
// a text is the same, the key is the same and the sentence is theirs, so a correction on
// either side is one edit rather than two. The rest is written here.
import { LLM } from "./gen";
import type { Overlay } from "./i18n";

/** Words that exist only in the build that carries a language model.
 *
 *  Behind the same build-time gate as the branch they describe, and for the same reason: a
 *  table is data, so a translation naming a model would sit in the bundle whether or not
 *  the branch does, and the released build must carry no model name at all. `LLM` folds to
 *  a constant, so this object folds away with it. */
const GEN_WORDS_DE: Overlay = LLM ? {
  "ui.extraction.a-local-language-model": "Ein lokales Language Model liest Fließtext und gibt strukturierte Entitäten aus.",
  "ui.model.delete-cached-language-model": "Zwischengespeicherte Language-Model-Dateien aus diesem Browser löschen (behebt einen vollen oder beschädigten Cache)",
  "ui.model.qwen-webllm": "Qwen (WebLLM)",
  "ui.model.reads-free-form-prose": "Liest freien Fließtext und gibt strukturierte Entitäten aus — am besten bei erzählenden Dokumenten. Groß (~0,25–2,2 GB); WebGPU empfohlen; läuft in einem Hintergrund-Worker.",
  "ui.model.server-address": "Serveradresse",
  "ui.model.smart-engine-language-model": "Smart engine · Language model",
  "ui.model.smollm": "SmolLM2",
} : {};

export const ENGINE_WORDS: Record<string, Overlay> = {
  de: {
    // ── app ──
    "ui.app.loading": "Lädt …",

    // ── assetheatmap ──
    "ui.assetheatmap.asset-criticality": "Kritikalität der Assets",
    "ui.assetheatmap.collapse": "Einklappen",
    "ui.assetheatmap.expand-dependencies": "Abhängigkeiten aufklappen",
    "ui.assetheatmap.open": "Öffnen",
    "ui.assetheatmap.your-business-assets-ranked": "Ihre Business assets nach Kritikalität geordnet (das kritischste zuerst). Ein Klick auf eine Kachel zeigt die Supporting assets, von denen sie abhängt — damit Sie dem folgen können, was wirklich trägt.",

    // ── attackpaths ──
    "ui.attackpaths.attack-paths": "Attack paths",
    "ui.attackpaths.chains": "Ketten",
    "ui.attackpaths.choke-points": "Choke points",
    "ui.attackpaths.cross-chain-link": "kettenübergreifende Verbindung",
    "ui.attackpaths.kill-chain-link": "Verbindung innerhalb der Kette",
    "ui.attackpaths.no-kill-chain-steps": "Noch keine Kill-chain-Schritte — modellieren Sie die Kill chain eines Operational scenario, um seine Attack paths zu sehen.",
    "ui.attackpaths.read-only-projection-of": "nur lesende Projektion aller Angriffsketten auf die Zielobjekte",
    "ui.attackpaths.target-assets": "Zielobjekte",
    "ui.attackpaths.toggle-a-scenario-above": "Schalten Sie oben ein Szenario ein, um seinen Attack path zu zeigen, und fügen Sie weitere hinzu, um zu sehen, wo sie zusammenlaufen.",

    // ── caldepth ──
    "ui.caldepth.for-an-attack-that": "für einen Angriff, der für sich jemanden verlangt, der besser ist als die Hälfte aller Angreifer, versucht von einem fähigen",
    "ui.caldepth.how-well-the-step": "wie gut der Schritt geschützt ist",
    "ui.caldepth.implementation": "Implementierung",
    "ui.caldepth.measures-on-the-same": "Maßnahmen auf demselben Schritt",
    "ui.caldepth.of-every-attempts-how": "von je 100 Versuchen, wie viele durchkommen",

    // ── calibration ──
    "ui.calibration.add-an-exception": "+ Ausnahme hinzufügen",
    "ui.calibration.adds-a-stated-assumption": "fügt eine benannte Annahme hinzu,",
    "ui.calibration.by-tactic-used-where": "Nach Tactic — benutzt, wo eine Technique unten nicht aufgeführt ist:",
    "ui.calibration.chance-that-a-loss": "Wahrscheinlichkeit, dass ein Loss event einen Folgeschaden nach sich zieht:",
    "ui.calibration.each-table-is-graded": "Jede Tabelle ist nach ihrer Grundlage eingestuft:",
    "ui.calibration.everything-below-rests-on": "Alles Folgende ruht auf einem Gedanken. Ein Angriff braucht ein bestimmtes Können, um an einem Schritt vorbeizukommen, und eine Sicherheitsmaßnahme hebt dieses Niveau.",
    "ui.calibration.how-much-a-measure": "Wie viel eine Maßnahme in jeder Phase ihrer Einführung zählt, gemessen an einer fertigen:",
    "ui.calibration.how-often-a-scenario": "Wie oft ein Szenario versucht wird",
    "ui.calibration.how-the-default-was": "Wie der Vorgabewert zustande kam.",
    "ui.calibration.is-a-published-figure": "ist eine veröffentlichte Zahl mit dokumentierter Herleitung,",
    "ui.calibration.no-objectives-modelled-the": "Keine Objectives modelliert — die Relevance-Bewertung des Akteurs steht stellvertretend:",
    "ui.calibration.parameter-adjustment-the-settings": "Parametrierung - die Einstellungen, aus denen die Zahlen berechnet werden",
    "ui.calibration.parameter-adjustment-what-a": "Parametrierung - was eine Maßnahme wert ist und was Schichten davon zusammen ergeben",
    "ui.calibration.preventive-measures-are-the": "Preventive Maßnahmen sind die fünfte Klasse; was sie wert sind, steht in der Defence-in-depth-Tabelle darüber, weil es davon abhängt, wie viele auf einem Schritt sitzen.",
    "ui.calibration.remove-this-exception": "Diese Ausnahme entfernen",
    "ui.calibration.reset-this-table": "diese Tabelle zurücksetzen",
    "ui.calibration.source": "Quelle.",
    "ui.calibration.tactics-that-count-as": "Tactics, die als Drinbleiben zählen:",
    "ui.calibration.the-taxonomy-defines-which": "Die Taxonomy legt fest, welche Felder es gibt; die Calibration legt fest, wie ihre Werte zu Zahlen werden.",
    "ui.calibration.what-a-measure-is": "Was eine Maßnahme wert ist, und was ein Schaden kostet",
    "ui.calibration.what-an-attempt-is": "Wogegen ein Versuch ankommt",
    "ui.calibration.what-it-changes": "Was sich damit ändert.",

    // ── calinputs ──
    "ui.calinputs.type-an-exact-value": "Einen genauen Wert eingeben",

    // ── canvas ──
    "ui.canvas.new-type": "Neu: {0}",
    "ui.canvas.back-to-the-wheel": "Zurück auf 100 % — das Rad zoomt, Ziehen des Hintergrunds verschiebt",
    "ui.canvas.click-a-node-to": "Klicken Sie einen Knoten an, um seine Ketten zu verfolgen — mehrere wählen verengt viele Pfade auf einen.",

    // ── catalogadd ──
    "ui.catalogadd.choose-from-a-catalog": "Aus einem Katalog wählen",
    "ui.catalogadd.close": "Schließen",
    "ui.catalogadd.create-custom": "Eigenen anlegen…",
    "ui.catalogadd.documents": "Dokumente",
    "ui.catalogadd.import-a-framework-file": "Rahmenwerk-Dateien liest der Bereich",

    // ── catalogimport ──
    "ui.catalogimport.adds-what-this-catalogue": "fügt hinzu, was dieser Katalog trägt, und behält das Übrige.",
    "ui.catalogimport.choose-file": "Datei wählen…",
    "ui.catalogimport.close": "Schließen",
    "ui.catalogimport.documents-semi-deterministic-import": "Dokumente · halbdeterministischer Import",
    "ui.catalogimport.download-template": "Vorlage herunterladen",
    "ui.catalogimport.extend": "Erweitern",
    "ui.catalogimport.framework-name-optional": "Name des Frameworks (optional)",
    "ui.catalogimport.from-the-publisher": "Vom Herausgeber.",
    "ui.catalogimport.import-a-framework-catalog": "Framework / Katalog importieren",
    "ui.catalogimport.import-as": "Importieren als",
    "ui.catalogimport.joined-in-column-order": "In Spaltenreihenfolge zusammengefügt. Ein Teil, der nur wiederholt, was schon steht, bleibt weg.",
    "ui.catalogimport.map-columns": "Spalten zuordnen",
    "ui.catalogimport.only-checked-items-go": "nur angehakte Einträge gehen in die Tabelle",
    "ui.catalogimport.parse": "Einlesen",
    "ui.catalogimport.paste-a-table-csv": "Fügen Sie eine Tabelle (CSV/TSV) oder JSON ein, oder wählen Sie eine Datei — CSV, JSON, Text, oder ein PDF- oder Word-Dokument, dessen Text zuerst extrahiert wird. Werte werden gelesen",
    "ui.catalogimport.replace": "Ersetzen",
    "ui.catalogimport.sections-found": "Gefundene Abschnitte",
    "ui.catalogimport.select-what-to-add": "Wählen, was hinzukommt",
    "ui.catalogimport.takes-its-list-as": "nimmt seine Liste als das Ganze und verwirft, was sie nicht nennt - richtig für das Regelwerk, zu dem das Feld gehört, falsch für jedes andere, denn ein fremder Katalog nennt keinen dieser Begriffe, ohne dass das ihre Rücknahme bedeutet. In beiden Fällen bleibt ein Wert erhalten, den ein Datensatz noch trägt, und die Datensätze werden sonst nicht angefasst.",
    "ui.catalogimport.the-catalogue-is-fetched": "Der Katalog wird geholt, wenn Sie dies drücken, und sonst nicht — die Anwendung fragt von sich aus nichts an und funktioniert ohne Netz.",
    "ui.catalogimport.the-option-lists-of": "die Optionslisten der Felder, die eine Quelle nennen",
    "ui.catalogimport.the-vocabularies-this-catalogue": "Die Vokabulare dieses Katalogs sind bereits die, die dieser Build anbietet — nichts nachzuziehen.",
    "ui.catalogimport.vocabularies-this-catalogue-defines": "Vokabulare, die dieser Katalog festlegt",

    // ── changehistory ──
    "ui.changehistory.hash-chain-broken-at": "Hashkette bei Eintrag {0} unterbrochen - ein Eintrag wurde verändert, entfernt oder umgestellt",
    "ui.changehistory.hash-chain-intact-and": "Hashkette unversehrt und deckungsgleich mit den Daten",
    "ui.changehistory.the-log-knows-nothing": "Das Protokoll weiß nichts von diesem Datensatz - er kam von außen in die Datei. Importieren Sie sie erneut und bestätigen Sie, um ihn ins Protokoll zu nehmen.",
    "ui.changehistory.the-values-no-longer": "Die Werte stimmen nicht mehr mit dem überein, was das Protokoll zuletzt festgehalten hat - die Datei wurde außerhalb der Anwendung bearbeitet. Importieren Sie sie erneut und bestätigen Sie die Änderungen, um die Kette wiederherzustellen.",
    "ui.changehistory.changed-outside-the-app": "außerhalb der Anwendung geändert",
    "ui.changehistory.close": "Schließen",
    "ui.changehistory.integrity-verified": "Integrität bestätigt",
    "ui.changehistory.log-altered": "Protokoll verändert",
    "ui.changehistory.no-changes-recorded-yet": "Noch keine Änderungen aufgezeichnet.",
    "ui.changehistory.not-in-the-log": "nicht im Protokoll",

    // ── completeness ──
    "ui.completeness.completeness-gaps-in-the": "Lücken in der Vollständigkeit der Analyse, mit den betroffenen Einträgen und dem Weg, sie zu schließen. Alles hier ist aus der Studie abgeleitet — beheben Sie es an der Quelle.",
    "ui.completeness.quality-checks": "Qualitätsprüfungen",

    // ── coveragematrix ──
    "ui.coveragematrix.coverage": "Coverage",
    "ui.coveragematrix.coverage-traceability": "Abdeckung und Nachvollziehbarkeit",
    "ui.coveragematrix.framework": "Framework",
    "ui.coveragematrix.gaps-only": "Nur Lücken",
    "ui.coveragematrix.no-requirements-yet-add": "Noch keine Requirements — fügen Sie sie in der Requirements-Tabelle oben hinzu (etwa „+ From framework…“).",
    "ui.coveragematrix.only-the-requirements-no": "Nur die Requirements, die keine Maßnahme erfüllt",

    // ── dashboard ──
    "ui.dashboard.analysis-perimeter-scope": "Betrachtungsbereich / Geltungsbereich",
    "ui.dashboard.cancel": "Abbrechen",
    "ui.dashboard.clear-all-locally-stored": "Alle lokal gespeicherten Daten löschen und neu laden",
    "ui.dashboard.create": "Anlegen",
    "ui.dashboard.create-your-first-ebios": "Legen Sie Ihre erste Studie an, laden Sie das Beispiel oder importieren Sie eine",
    "ui.dashboard.delete": "Löschen",
    "ui.dashboard.load-sample-study": "Beispielstudie laden",
    "ui.dashboard.new-study": "Neue Studie",
    "ui.dashboard.no-studies-yet": "Noch keine Studien",
    "ui.dashboard.not-set-no-sector": "Nicht gesetzt — keine Branchenanpassung",
    "ui.dashboard.organization": "Organisation",
    "ui.dashboard.reset": "Zurücksetzen",
    "ui.dashboard.risk-studies": "Risikostudien",
    "ui.dashboard.sector": "Branche",
    "ui.dashboard.some-kinds-of-attacker": "Manche Angreifer suchen sich bestimmte Branchen weit gezielter aus als andere. Wird von den Basisraten der Quantifizierung benutzt; später in der Calibration änderbar.",
    "ui.dashboard.study-name": "Name der Studie",
    "ui.dashboard.what-is-in-scope": "Was gehört dazu? Welche Systeme, Prozesse, Grenzen?",

    // ── datamenu ──
    "ui.datamenu.each-of-them-opens": "Jeder von ihnen öffnet sie mit seinem eigenen Schlüssel. Die Liste der Empfänger ist in der Datei lesbar — daran erkennt man, ob sie an jemanden ging, den man nicht erwartet hat.",
    "ui.datamenu.file-or-paste": "Datei oder Einfügen",
    "ui.datamenu.format": "Format",
    "ui.datamenu.import-data": "Daten importieren…",
    "ui.datamenu.key": "Schlüssel",
    "ui.datamenu.none": "Keiner",
    "ui.datamenu.password": "Passwort",
    "ui.datamenu.password-aes": "Passwort (AES-256)",
    "ui.datamenu.portable-session": "Portable Sitzung",
    "ui.datamenu.protection": "Schutz",
    "ui.datamenu.taxonomy": "Taxonomy",
    "ui.datamenu.taxonomy-data-docs-settings": "Taxonomie + Daten + Dokumente + Einstellungen",

    // ── distinput ──
    "ui.distinput.drag-to-slide-the": "Ziehen, um die ganze Verteilung zu verschieben",

    // ── documents ──
    "ui.documents.n-for-this-study": "{0} für diese Studie · Word / PDF / Text - lokal extrahiert und zwischengespeichert",
    "ui.documents.references.many": "{0} Fundstellen",
    "ui.documents.references.one": "{0} Fundstelle",
    "ui.documents.add-a-reference-to": "Fügen Sie eine Referenz auf ein Quelldokument hinzu, um Ihre Bibliothek zu beginnen.",
    "ui.documents.add-document": "Dokument hinzufügen…",
    "ui.documents.add-reference": "Referenz hinzufügen",
    "ui.documents.add-word-pdf-or": "Word-, PDF- oder Textdateien hinzufügen (der Text wird lokal extrahiert, vollständig offline). Das erste Dokument legt eine neue Studie an, die den Korpus hält.",
    "ui.documents.added": "Hinzugefügt",
    "ui.documents.can-read-it-instantly": "kann es sofort lesen - nichts wird hochgeladen. Klicken Sie",
    "ui.documents.documents": "Dokumente",
    "ui.documents.extract": "Extrahieren",
    "ui.documents.import-a-document-corpus": "Dokumentkorpus importieren",
    "ui.documents.import-a-requirement-measure": "Ein Requirement-/Measure-Framework aus einer Tabelle importieren (CSV/TSV/JSON)",
    "ui.documents.import-framework": "Framework importieren",
    "ui.documents.name": "Name",
    "ui.documents.no-references-yet": "Noch keine Referenzen",
    "ui.documents.on-a-reference-to": "auf eine Fundstelle, um Entitäten für die aktive Studie vorzuschlagen.",
    "ui.documents.reference-library": "Referenzbibliothek",
    "ui.documents.references": "Referenzen",
    "ui.documents.references-keep-each-source": "Referenzen behalten Name, Typ und Größe jedes Quelldokuments. Für",
    "ui.documents.remove": "Entfernen",
    "ui.documents.size": "Größe",
    "ui.documents.the-plain-text-is": "der reine Text wird außerdem lokal zwischengespeichert (offline, in Ihrem Browser), damit",
    "ui.documents.type": "Typ",

    // ── entity ──
    "ui.entity.back": "Zurück",
    "ui.entity.cancel": "Abbrechen",
    "ui.entity.change-note": "Änderungsnotiz",
    "ui.entity.close": "Schließen",
    "ui.entity.delete": "Löschen",
    "ui.entity.editor": "Bearbeiter",
    "ui.entity.extracted-from-this-source": "Aus dieser Quelle extrahiert",
    "ui.entity.open": "Öffnen",
    "ui.entity.referenced-by": "Verwiesen von",

    // ── entityinfo ──
    "ui.entityinfo.close": "Schließen",
    "ui.entityinfo.edit": "Bearbeiten",
    "ui.entityinfo.relationships": "Beziehungen",

    // ── entitysection ──
    "ui.entitysection.disable-record": "{0} deaktivieren",
    "ui.entitysection.enable-record": "{0} aktivieren",
    "ui.entitysection.currently-in-use.one": "Wird derzeit von {0} Datensatz gebraucht",
    "ui.entitysection.currently-in-use.many": "Wird derzeit von {0} Datensätzen gebraucht",
    "ui.entitysection.taking-it-out-anyway": "Trotzdem herauszunehmen nimmt {0} mit - {1} Datensätze insgesamt.",
    "ui.entitysection.that-one.one": "diesen einen",
    "ui.entitysection.that-one.many": "diese {0}",
    "ui.entitysection.disabled-with-it.one": "Mit deaktiviert ({0})",
    "ui.entitysection.disabled-with-it.many": "Mit deaktiviert ({0})",
    "ui.entitysection.also-affected.one": "Ebenfalls betroffen ({0})",
    "ui.entitysection.also-affected.many": "Ebenfalls betroffen ({0})",
    "ui.entitysection.out-of-scope-anyway.one": "Trotzdem herausnehmen ({0})",
    "ui.entitysection.out-of-scope-anyway.many": "Trotzdem herausnehmen ({0})",
    "ui.entitysection.disable": "Deaktivieren",
    "ui.entitysection.enable": "Aktivieren",
    "ui.entitysection.deleted-with-it.one": "Mit gelöscht ({0}) - das lässt sich nicht rückgängig machen",
    "ui.entitysection.deleted-with-it.many": "Mit gelöscht ({0}) - das lässt sich nicht rückgängig machen",
    "ui.entitysection.these-stay-and-lose.one": "Diese bleiben und verlieren ihre Verknüpfung dorthin ({0})",
    "ui.entitysection.these-stay-and-lose.many": "Diese bleiben und verlieren ihre Verknüpfung dorthin ({0})",
    "ui.entitysection.more.one": "+{0} weiterer",
    "ui.entitysection.more.many": "+{0} weitere",
    "ui.entitysection.none-left": "keine mehr",
    "ui.entitysection.emptied": "geleert",
    "ui.entitysection.n-others.one": "{0} weiterer",
    "ui.entitysection.n-others.many": "{0} weitere",
    "ui.entitysection.n-left.one": "{0} übrig",
    "ui.entitysection.n-left.many": "{0} übrig",
    "ui.entitysection.a-type-involved-has": "Ein beteiligter Typ hat in dieser Taxonomy keinen Schalter.",
    "ui.entitysection.cancel": "Abbrechen",
    "ui.entitysection.change-history": "Änderungsverlauf",
    "ui.entitysection.clear-filters": "Filter zurücksetzen",
    "ui.entitysection.counts-again-everywhere": "Zählt überall wieder mit.",
    "ui.entitysection.delete": "Löschen",
    "ui.entitysection.details": "Details",
    "ui.entitysection.edit": "Bearbeiten",
    "ui.entitysection.extracted-from-this-source": "Aus dieser Quelle extrahiert",
    "ui.entitysection.nothing-else-is-affected": "Sonst ist nichts betroffen.",
    "ui.entitysection.nothing-in-the-study": "Nichts in der Studie verweist darauf. Löschen entfernt genau diesen Datensatz, und die Löschung wird protokolliert.",
    "ui.entitysection.nothing-matches": "Nichts passt.",
    "ui.entitysection.open": "Öffnen",
    "ui.entitysection.referenced-by": "Verwiesen von",
    "ui.entitysection.this-record-alone-is": "Nur dieser Datensatz wird gelöscht.",
    "ui.entitysection.to-keep-the-record": "Um den Datensatz mitsamt seiner Bewertung aus den Zahlen herauszuhalten, setzen Sie ihn stattdessen zurück.",
    "ui.entitysection.view": "Ansehen →",

    // ── extraction ──
    "ui.extraction.best-and-second-best": "Bester und zweitbester Typ lagen dicht beieinander — bitte prüfen",
    "ui.extraction.cancel": "Abbrechen",
    "ui.extraction.close": "Schließen",
    "ui.extraction.document-name": "Name des Dokuments",
    "ui.extraction.embeddings-classify-sentences-into": "Embeddings ordnen Sätze der Taxonomy zu — am besten bei strukturierten, listenartigen Dokumenten.",
    "ui.extraction.engine": "Engine",
    "ui.extraction.extract-entities": "Entitäten extrahieren",
    "ui.extraction.fast-engine": "Fast engine.",
    "ui.extraction.model": "Model",
    "ui.extraction.models-are-managed-in": "Models werden verwaltet im",
    "ui.extraction.no-candidates-found": "Keine Kandidaten gefunden.",
    "ui.extraction.no-extraction-model-is": "Es ist kein Extraktions-Model geladen.",
    "ui.extraction.open-file": "Datei öffnen",
    "ui.extraction.paste-document-text-or": "Dokumenttext einfügen, oder „Datei öffnen“ benutzen (der Inhalt wird nur flüchtig gelesen, nicht gespeichert)…",
    "ui.extraction.stop": "Anhalten",
    "ui.extraction.text": "Text",
    "ui.extraction.the-passage-could-not": "Die Stelle war im aktuellen Text nicht auffindbar — er wurde womöglich seit der Extraktion bearbeitet.",

    // ── factortrace ──
    "ui.factortrace.a-step-is-only": "Ein Schritt ist nur dann eine weitere Hürde, wenn ihn dort etwas blockiert oder entdeckt. Schritte, an denen nichts hängt, kosten ihn nichts — die Kette feiner zu zerlegen macht sie also nicht schwerer.",
    "ui.factortrace.attempts-per-year": "Versuche pro Jahr",
    "ui.factortrace.breadth": "Breite",
    "ui.factortrace.capped-the-multipliers-together": "Gedeckelt: die Multiplikatoren zusammen ergaben eine Rate, die kein einzelnes Szenario plausibel erreicht — meist heißt das, eine der Bewertungen ist zu hoch.",
    "ui.factortrace.close": "Schließen",
    "ui.factortrace.factor": "Faktor",
    "ui.factortrace.getting-in": "Hineinkommen",
    "ui.factortrace.how-it-s-calculated": "Wie es gerechnet wird",
    "ui.factortrace.how-often-this-scenario": "Wie oft dieses Szenario versucht wird. Eine Zahl, nicht zwei: wie oft Kontakt entsteht und wie oft aus Kontakt ein Versuch wird, lässt sich nicht getrennt schätzen.",
    "ui.factortrace.of-the-field-before": "des Feldes, bevor eine Ihrer Maßnahmen zählt. Jede Maßnahme kommt dann an dem Schritt hinzu, auf dem sie sitzt.",
    "ui.factortrace.of-the-field-model": "des Feldes. Modellieren Sie die Kette, und dies wird abgeleitet statt eingeschätzt.",
    "ui.factortrace.reset-to-derived": "↺ auf abgeleitet zurücksetzen",
    "ui.factortrace.seeded-from-the-feared": "Vorbelegt aus der Schwere des Schadensereignisses",
    "ui.factortrace.staying-in": "Drinbleiben",
    "ui.factortrace.the-difficulty-rating-stands": "Die Difficulty-Bewertung steht stellvertretend:",
    "ui.factortrace.the-entry-technique": "· die Einstiegstechnik",
    "ui.factortrace.the-factor-you-are": "der Faktor, den Sie verfolgen - er speist die Schritte darunter",
    "ui.factortrace.tooling": "Werkzeug",
    "ui.factortrace.what-the-attack-demands": "Was der Angriff verlangt",
    "ui.factortrace.what-the-attack-itself": "Was der Angriff selbst verlangt, abgelesen an der Kette unten: ein Angreifer muss etwa",
    "ui.factortrace.where-it-comes-from": "Woher es kommt",

    // ── frameworkradar ──
    "ui.frameworkradar.framework-coverage": "Framework-Coverage",
    "ui.frameworkradar.requirements-fulfilled-per-framework": "erfüllte Anforderungen je Rahmenwerk",

    // ── graph ──
    "ui.graph.click-to-inspect-double": "· anklicken zum Ansehen · Doppelklick zentriert neu · Umschalt-Klick vergleicht",
    "ui.graph.n-relationships.many": "{0} Beziehungen",
    "ui.graph.n-relationships.one": "{0} Beziehung",
    "ui.graph.shift-click-to-add": "Umschalt-Klick nimmt es in den Fokus auf",
    "ui.graph.add-entities-in-the": "Legen Sie Entitäten in den Workshops an — der Graph wächst mit ihnen.",
    "ui.graph.clear-extra": "Zusätzliche entfernen",
    "ui.graph.no-matches": "Keine Treffer.",
    "ui.graph.no-relationships-yet": "noch keine Beziehungen",
    "ui.graph.nothing-to-show-yet": "Noch nichts zu zeigen",
    "ui.graph.search-entities": "Entitäten suchen…",

    // ── import ──
    "ui.import.a-key-you-have": ", ein Schlüssel, für den Sie gebürgt haben",
    "ui.import.check-against-a-key": "Gegen eine Schlüsseldatei prüfen…",
    "ui.import.choose-a-source-to": "Wählen Sie eine Quelle, um die Änderungen zuerst anzusehen.",
    "ui.import.choose-file": "Datei wählen…",
    "ui.import.close": "Schließen",
    "ui.import.complete-and-matches-its": "vollständig und stimmt mit seinen Daten überein",
    "ui.import.data-json-yaml-auto": "Daten · JSON / YAML (automatisch erkannt)",
    "ui.import.hold-the-sender-s": "Halten Sie den öffentlichen Schlüssel des Absenders? Prüfen Sie ihn gegen dieses Siegel.",
    "ui.import.its-history-is-taken": ". Ihr Verlauf wird übernommen, wie er ist, und was sie unbelegt lässt, wird vermerkt als",
    "ui.import.no-differences": "Keine Unterschiede.",
    "ui.import.no-study-data-in": "Keine Studiendaten in dieser Datei (nur Taxonomy/Einstellungen).",
    "ui.import.not-sealed": "Nicht versiegelt.",
    "ui.import.not-verified": "Nicht verifiziert",
    "ui.import.nothing-in-this-file": "Nichts in dieser Datei sagt, wer sie erzeugt hat; ihr Änderungsprotokoll lässt sich nur gegen sich selbst prüfen.",
    "ui.import.paste-a-bundle-study": "Fügen Sie hier ein Bundle, Studiendaten oder eine Taxonomy ein…",
    "ui.import.paste-json-yaml": "JSON / YAML einfügen",
    "ui.import.preview-a-demo-revision": "Eine Beispiel-Revision ansehen",
    "ui.import.preview-pasted": "Eingefügtes ansehen →",
    "ui.import.see-the-diff-without": "Den Unterschied sehen, ohne eine Datei zu bearbeiten",
    "ui.import.signature-valid-sender-unconfirmed": "Signatur gültig, Absender unbestätigt",
    "ui.import.source": "Quelle",
    "ui.import.the-file-s-own": "der eigene Änderungslauf der Datei ist",
    "ui.import.the-seal-is-intact": "— das Siegel ist unversehrt, aber dieser Schlüssel ist keiner, den Sie benannt haben",
    "ui.import.this-file-s-change": "der Änderungslauf dieser Datei",
    "ui.import.verified": "Verifiziert",

    // ── killchainlane ──
    "ui.killchainlane.drag-steps-from-the": "Schritte aus der Tabelle oder zwischen Kacheln ziehen →",
    "ui.killchainlane.drag-to-a-tactic": "Auf eine Tactic-Kachel ziehen · zum Bearbeiten klicken",
    "ui.killchainlane.step": "Schritt",
    "ui.killchainlane.unassigned": "Nicht zugeordnet",

    // ── killchainmitigation ──
    "ui.killchainmitigation.expand-a-scenario-to": "ein Szenario aufklappen, um jedem Schritt Maßnahmen zuzuweisen",
    "ui.killchainmitigation.kill-chain-mitigation": "Kill-chain-Mitigation",
    "ui.killchainmitigation.mitigation": "Mitigation",
    "ui.killchainmitigation.no-kill-chain-steps": "Noch keine Kill-chain-Schritte in diesem Szenario — legen Sie sie unter Operational Scenarios an.",
    "ui.killchainmitigation.no-operational-scenarios-yet": "Noch keine Operational scenarios.",
    "ui.killchainmitigation.operational-scenario": "Operational scenario",

    // ── mitigationcharts ──
    "ui.mitigationcharts.n-detect-him.many": "{0} erkennen ihn",
    "ui.mitigationcharts.n-detect-him.one": "{0} erkennt ihn",
    "ui.mitigationcharts.n-steps-block.many": "{0} von {1} Schritten halten einen Angreifer auf",
    "ui.mitigationcharts.n-steps-block.one": "{0} von {1} Schritten hält einen Angreifer auf",
    "ui.mitigationcharts.both-move-the-risk": ". Beides verschiebt die Risikozahlen; keines ändert, ob dieser Schritt erreicht wird.",
    "ui.mitigationcharts.attempts-this-chain-stops": "Versuche, die diese Kette aufhält",
    "ui.mitigationcharts.break-down-per-scenario": "Nach Szenario aufschlüsseln",
    "ui.mitigationcharts.defended-click-to-see": "verteidigt - anklicken für die Rechnung",
    "ui.mitigationcharts.hide-per-scenario": "Aufschlüsselung schließen",
    "ui.mitigationcharts.a-second-measure-on": "Eine zweite Maßnahme am selben Schritt schließt einen Teil dessen, was die erste offen ließ. Jede zählt danach, wie weit sie umgesetzt ist und wo sie greift.",
    "ui.mitigationcharts.all-scenarios": "Alle Szenarien",
    "ui.mitigationcharts.at-this-step": "an diesem Schritt",
    "ui.mitigationcharts.chain-defence": "Verteidigung der Kette",
    "ui.mitigationcharts.click-a-tile-for": "eine Kachel anklicken für die Rechnung",
    "ui.mitigationcharts.close": "Schließen",
    "ui.mitigationcharts.corrective-deterrent-and-avoidance": "Corrective-, deterrent- und avoidance-Maßnahmen werden hier nicht gezählt",
    "ui.mitigationcharts.corrective-measures-act-on": "korrigierende Maßnahmen wirken auf den Schaden",
    "ui.mitigationcharts.damage-control-what-the": "(Schadensbegrenzung: was der Angriff kostet, sobald er gelingt),",
    "ui.mitigationcharts.damage-control-what-the-2": "(Schadensbegrenzung: was der Angriff kostet, sobald er gelingt), abschreckende und vermeidende auf",
    "ui.mitigationcharts.defense-in-depth-per": "Defense in depth — je Kill-chain-Schritt",
    "ui.mitigationcharts.detected-in-time": "rechtzeitig erkannt",
    "ui.mitigationcharts.deterrent-and-avoidance-measures": "abschreckende und vermeidende Maßnahmen wirken auf die Zahl der Angriffe",
    "ui.mitigationcharts.no-measure-fully-open": "keine Maßnahme - vollständig offen",
    "ui.mitigationcharts.no-tactics-assigned-to": "Den Kill-chain-Schritten sind noch keine Tactics zugeordnet.",
    "ui.mitigationcharts.nothing-blocks-or-detects": "hier blockiert oder erkennt nichts einen Angreifer",
    "ui.mitigationcharts.outcome-of-an-attack": "Ausgang eines Angriffsversuchs, aus derselben Traversierung wie die Risikozahlen",
    "ui.mitigationcharts.per-step-blocks-detects": "je Schritt: 1 − (1 − blockiert) × (1 − erkannt)",
    "ui.mitigationcharts.preventive-ones-block-him": ": vorbeugende blockieren ihn, detektierende ertappen ihn. Die übrigen bekommen keinen Balken, weil sie auf einen anderen Faktor wirken -",
    "ui.mitigationcharts.reaches-the-objective": "erreicht das Ziel",
    "ui.mitigationcharts.the-bar-counts-only": "Der Balken zählt nur Maßnahmen, die einen Angreifer aufhalten",
    "ui.mitigationcharts.the-number-of-attacks": "die Zahl der Angriffe",
    "ui.mitigationcharts.they-act-on-a": "- sie wirken auf einen anderen Faktor. Korrigierende wirken auf",
    "ui.mitigationcharts.this-measures-how-consistently": "Das misst, wie durchgängig die Schritte einer Tactic verteidigt sind, nicht wie wahrscheinlich ein Angriff scheitert — das hängt auch davon ab, wo er ansetzt.",
    "ui.mitigationcharts.ttp-tactic-defence": "Verteidigung nach TTP-Tactic",

    // ── model ──
    "ui.model.keeping-the-model-as-a-file": "Damit es nicht in jeder {0}-Sitzung erneut geladen werden muss, liegt das Modell als Datei ({1}): {2} drücken, die Datei aus dem Speichern-Dialog neben diese HTML-Seite legen und beim nächsten Mal {3} drücken. Das funktioniert in Chrome und Edge, auch unter {0}. Unter {4} und in Firefox wird die Datei beim Start gefunden.",
    "ui.model.load-the-model-first": "Erst das Modell laden",
    "ui.model.reload": "Neu laden",
    "ui.model.save-as-a-file": "Als Datei neben der Anwendung speichern",
    "ui.model.working": "Arbeitet…",
    "ui.model.downloaded-not-loaded": "Heruntergeladen · nicht geladen",
    "ui.model.loaded": "Geladen",
    "ui.model.not-downloaded": "Nicht heruntergeladen",
    "ui.model.add": "Hinzufügen",
    "ui.model.add-model": "Model hinzufügen…",
    "ui.model.ai-offline": "KI · offline",
    "ui.model.cancel": "Abbrechen",
    "ui.model.classifies-sentences-into-the": "Ordnet Sätze der Taxonomy zu — am besten bei strukturierten, listenartigen Dokumenten. Klein (~25–34 MB).",
    "ui.model.clear": "Leeren",
    "ui.model.download-load": "Herunterladen und laden",
    "ui.model.fast-engine-embeddings": "Fast engine · Embeddings",
    "ui.model.label": "Bezeichnung",
    "ui.model.look-again": "Erneut suchen",
    "ui.model.models": "Models",
    "ui.model.note": "Notiz",
    "ui.model.pick-an-existing-aurelian": "Eine vorhandene aurelian-model.bin wählen — wird ohne Download wiederverwendet (funktioniert auch auf file://)",
    "ui.model.remove-this-model": "Dieses Model entfernen",
    "ui.model.save-file": "Datei speichern",
    "ui.model.size": "Größe",
    "ui.model.the": "Das",
    "ui.model.two-independent-engines-load": "Zwei unabhängige Engines — laden Sie eine oder beide. Alles läuft lokal in Ihrem Browser.",
    "ui.model.use-file": "Datei benutzen…",

    // ── modelling ──
    "ui.modelling.and-all-are-recorded": " und alle sind erfasst",
    "ui.modelling.object": "Objekt",
    "ui.modelling.of-which-n-are-not": ", davon {0} noch nicht erfasst",
    "ui.modelling.states-per-requirement-which": "{0} gibt je Anforderung an, für welche Klassen von Objekten sie gilt. Jedes {1} unten wird mit seiner Klasse und jeder Klasse darüber gelesen, die Anforderungen dieser Klassen werden gesammelt, und was ein Objekt zweimal erreicht, wird einmal geführt. {2} gelten für diese Studie{3}.",
    "ui.modelling.class": "Klasse",
    "ui.modelling.derived-from-the-catalogue": "Aus dem Katalog abgeleitet",
    "ui.modelling.hide-the-account": "Die Herleitung verbergen",
    "ui.modelling.inherited": "Geerbt",
    "ui.modelling.requirements": "Requirements",
    "ui.modelling.show-the-account": "Die Herleitung zeigen",
    "ui.modelling.the-whole-ruleset-is": "Das ganze Regelwerk ist erfasst, und das Paket ist aktuell",

    // ── nav ──
    "ui.nav.documents-for-the-active": "Dokumente der aktiven Studie",
    "ui.nav.import-a-document-corpus": "Einen Dokumentenbestand einlesen (legt eine Studie an)",
    "ui.nav.browser-language": "Browsersprache",
    "ui.nav.change-timeline-of-the": "Änderungslauf der aktiven Studie",
    "ui.nav.documents": "Dokumente",
    "ui.nav.model": "Model",
    "ui.nav.navigation": "Navigation",
    "ui.nav.read-the-model-what": "Das Modell lesen: woraus es besteht, welche Felder die Veröffentlichung füllt, was die Klassen tragen, was worauf zeigt",
    "ui.nav.schema": "Schema",
    "ui.nav.studies": "Studien",
    "ui.nav.the-language-this-interface": "Die Sprache, in der diese Oberfläche gezeigt wird. Ohne Wahl folgt sie dem Browser.",
    "ui.nav.the-shape-this-application": "Die Form, in der diese Anwendung das Modell hält: Entitätstypen, ihre Felder und die Vokabulare dahinter",
    "ui.nav.theme.dark": "Dunkles Thema",
    "ui.nav.theme.light": "Helles Thema",
    "ui.nav.timeline": "Timeline",

    // ── quantification ──
    "ui.quantification.add-a-scenario-to": "Ein Szenario zur Quantifizierung hinzufügen",
    "ui.quantification.add-scenario": "Szenario hinzufügen",
    "ui.quantification.an-attacker-has-to": "ein Angreifer muss besser sein als dieser Anteil aller Angreifer",
    "ui.quantification.an-attempt-only-counts": "Ein Versuch zählt erst dann als Loss event, wenn er das Ende der Kette erreicht. Hineinzukommen ist kein Loss event.",
    "ui.quantification.annual-loss-log": "Jahresschaden (log €) →",
    "ui.quantification.attacker-capability": "Fähigkeit des Angreifers",
    "ui.quantification.attempts-per-year": "Versuche pro Jahr",
    "ui.quantification.being-spotted-here": "Hier entdeckt zu werden",
    "ui.quantification.cascading-impact": "Folgeschaden",
    "ui.quantification.cascading-likelihood": "Wahrscheinlichkeit des Folgeschadens",
    "ui.quantification.close": "Schließen",
    "ui.quantification.direct-impact": "Direkter Schaden",
    "ui.quantification.from-the-capability-rating": "aus der Fähigkeitsbewertung: schlimmstenfalls, wahrscheinlich, bestenfalls - besser als dieser Anteil aller Angreifer. Breit, weil eine Bewertung eine Klasse von Angreifern beschreibt, nicht eine Person.",
    "ui.quantification.how-much-skill-it": "Wie viel Können es braucht, um an diesem Schritt vorbeizukommen",
    "ui.quantification.how-much-skill-this": "Wie viel Können dieser Angriff für sich verlangt",
    "ui.quantification.how-skilled-this-attacker": "Wie fähig dieser Angreifer ist",
    "ui.quantification.inherent-no-controls": "Inherent (ohne Controls)",
    "ui.quantification.loss-event-frequency": "Loss event frequency",
    "ui.quantification.loss-events-per-year": "Schadensereignisse pro Jahr",
    "ui.quantification.loss-magnitude": "Loss magnitude",
    "ui.quantification.measured-over-the-simulation": "gemessen über die Simulation, nirgends gesetzt",
    "ui.quantification.measures-you-recorded-on": "Maßnahmen, die Sie an diesem Schritt erfasst haben",
    "ui.quantification.no-scenarios-quantified-yet": "Noch keine Szenarien quantifiziert",
    "ui.quantification.none-nothing-here-costs": "Keine. Nichts hier kostet einen Angreifer etwas.",
    "ui.quantification.nothing-on-this-chain": "Nichts auf dieser Kette hält einen Versuch auf — jeder Angreifer, der beginnt, kommt durch.",
    "ui.quantification.opt-in-per-scenario": "Aufnahme je Szenario",
    "ui.quantification.out-of-every-attacks": "von je 100 Angriffen auf diese Kette",
    "ui.quantification.out-of-every-attempts": "von je 100 Versuchen auf diese Kette",
    "ui.quantification.quantification-is-opt-in": "Quantification ist freiwillig — sie leitet eine monetäre Jahresschadenszahl nur für die Szenarien ab, die Sie auswählen. Benutzen Sie",
    "ui.quantification.quantitative-risk": "Quantitatives Risiko",
    "ui.quantification.remove-from-quantification": "Aus der Quantification entfernen",
    "ui.quantification.residual-with-controls": "Residual (mit Controls)",
    "ui.quantification.secondary-risk": "Sekundäres Risiko",
    "ui.quantification.simulated-annual-loss-distribution": "Simulierte Jahresschadensverteilung",
    "ui.quantification.skill-the-attack-needs": "Können, das der Angriff verlangt, vor jeder Ihrer Maßnahmen",
    "ui.quantification.the-chain-needs-persistence": "die Kette verlangt Persistenz, Umgehung oder seitliche Bewegung",
    "ui.quantification.the-full-quantification-as": "Die vollständige Quantification als Text: die Regeln, die geltenden Parameter, jeder abgeleitete Term, die Kette, die Ergebnisse und die genannten Grenzen",
    "ui.quantification.the-hardest-single-technique": "die schwierigste einzelne Technik der Kette",
    "ui.quantification.this-scenario-models-no": "dieses Szenario modelliert keine Kette, es gibt also nichts, woraus es abzuleiten wäre",
    "ui.quantification.to-pick-the-operational": "um die zu quantifizierenden Angriffsszenarien zu wählen.",
    "ui.quantification.trace-the-control-strength": "Die Control-Stärke nachverfolgen",
    "ui.quantification.vulnerability": "Vulnerability",
    "ui.quantification.what-an-attempt-has": "Wogegen ein Versuch ankommen muss",
    "ui.quantification.what-this-share-becomes": "Was aus diesem Anteil wird",
    "ui.quantification.where-the-attempts-are": "Wo die Versuche gestoppt werden",
    "ui.quantification.where-this-number-comes": "Woher diese Zahl kommt",
    "ui.quantification.you-rated-this-scenario": "Sie haben dieses Szenario bewertet mit",

    // ── radarchart ──
    "ui.radarchart.not-enough-data-yet": "Noch nicht genug Daten.",

    // ── riskmatrix ──
    "ui.riskmatrix.accept": "Accept",
    "ui.riskmatrix.avoid": "Avoid",
    "ui.riskmatrix.from-the-decision-how": "aus der Entscheidung und daraus, wie gut die Angriffskette des Risikos gemindert ist:",
    "ui.riskmatrix.inherent": "Inherent",
    "ui.riskmatrix.lowers-likelihood-by-that": "senkt die Eintrittswahrscheinlichkeit (um diese Abdeckung),",
    "ui.riskmatrix.reduce": "Reduce",
    "ui.riskmatrix.removes-it-untreated-risks": "entfernt es. Unbehandelte Risiken bleiben beim Ausgangswert. Für die Verschiebung auf eine Marke zeigen.",
    "ui.riskmatrix.residual": "Residual",
    "ui.riskmatrix.residual-position-after-treatment": "Restrisiko = Lage nach der Behandlung,",
    "ui.riskmatrix.risk-matrix": "Risk matrix",
    "ui.riskmatrix.share": "Share",

    // ── seal ──
    "ui.seal.create-or-load-a": "Erst einen Signaturschlüssel anlegen oder laden",
    "ui.seal.a-signature-carries-no": "Eine Signatur trägt keine Zeit; wer den Schlüssel hat, kann ein Seal datieren, wie er will.",
    "ui.seal.add-someone-s-public": "Öffentlichen Schlüssel einer anderen Person hinzufügen…",
    "ui.seal.anyone-can-check-a": "Jeder kann ein Seal ohne diese Anwendung prüfen: es ist ein JWS (ES256), und der öffentliche Schlüssel reist mit.",
    "ui.seal.cancel": "Abbrechen",
    "ui.seal.close": "Schließen",
    "ui.seal.compare-this-fingerprint-with": "Vergleichen Sie diesen Fingerabdruck mit dem, den sein Inhaber Ihnen genannt hat — telefonisch, persönlich, auf jedem Weg außer der Datei selbst. Ihn hier zu benennen heißt, dass Sie das getan haben.",
    "ui.seal.create-a-key": "Schlüssel erzeugen",
    "ui.seal.forget-this-key": "Diesen Schlüssel vergessen",
    "ui.seal.it-does-not-make": "Es macht den Inhalt nicht wahr.",
    "ui.seal.it-does-not-prove": "Es beweist nicht, wann.",
    "ui.seal.it-does-not-prove-2": "Es beweist für sich genommen nicht, wer.",
    "ui.seal.it-is-theirs": "Er gehört ihm",
    "ui.seal.it-makes-its-author": "Es macht seinen Urheber dafür verantwortlich.",
    "ui.seal.it-proves-the-history": "Es beweist die Historie.",
    "ui.seal.it-proves-the-holder": "Es beweist „der Inhaber dieses Schlüssels“. Vergleichen Sie den Fingerabdruck auf einem anderen Weg und benennen Sie dann den Schlüssel — danach lesen sich Seals von ihm als verifiziert.",
    "ui.seal.keys": "Schlüssel",
    "ui.seal.keys-you-have-named": "Schlüssel, die Sie benannt haben",
    "ui.seal.load-private-key": "Privaten Schlüssel laden…",
    "ui.seal.name-it": "Benennen…",
    "ui.seal.name-this-key": "Diesen Schlüssel benennen",
    "ui.seal.none-yet-name-a": "Noch keine. Benennen Sie einen Schlüssel aus einem Seal, oder laden Sie die Datei mit dem öffentlichen Schlüssel einer anderen Person.",
    "ui.seal.not-a-secret-hand": "kein Geheimnis — geben Sie ihn jedem, der Ihre Siegel prüft",
    "ui.seal.not-sealed-a-seal": "Nicht versiegelt. Ein Seal signiert das bisherige Änderungsprotokoll, sodass jede Änderung an bereits Aufgezeichnetem den privaten Schlüssel erfordert.",
    "ui.seal.or-load-one-you": "Oder einen laden, den Sie schon haben",
    "ui.seal.private-key": "Privater Schlüssel",
    "ui.seal.public-key": "Öffentlicher Schlüssel",
    "ui.seal.save-private-key": "Privaten Schlüssel speichern…",
    "ui.seal.save-public-key": "Öffentlichen Schlüssel speichern…",
    "ui.seal.seal": "Seal",
    "ui.seal.seal-as": "Versiegeln als",
    "ui.seal.seal-this-study": "Diese Studie versiegeln",
    "ui.seal.sealed-by": "Versiegelt von",
    "ui.seal.sealed-by-an-unnamed": "Von einem unbenannten Schlüssel gesiegelt",
    "ui.seal.seals": "Seals",
    "ui.seal.the-log-itself-does": "Das Protokoll selbst verifiziert nicht, ein Seal kann also nur für das sprechen, was vor dem Bruch liegt.",
    "ui.seal.the-password-its-file": "das Passwort, mit dem die Datei gespeichert wurde",
    "ui.seal.the-signature-covers-the": "Die Signatur deckt den Kopf des Änderungsprotokolls ab, also ist jeder vor dem Seal aufgezeichnete Eintrag genau das, was signiert wurde. Etwas davon zu ändern erfordert den Schlüssel.",
    "ui.seal.this-browser-exposes-no": "Dieser Browser bietet keine Web Crypto, hier lassen sich Studien nicht versiegeln.",
    "ui.seal.this-installation": "Diese Installation",
    "ui.seal.what-a-seal-proves": "Was ein Seal beweist",
    "ui.seal.what-does-a-seal": "Was beweist ein Seal?",
    "ui.seal.whose-key-is-it": "Wessen Schlüssel ist es?",

    // ── sectorsection ──
    "ui.sectorsection.applied-to-the-attack": "Auf die Angriffsrate angewandt:",
    "ui.sectorsection.not-set": "Nicht gesetzt",
    "ui.sectorsection.sector": "Branche",
    "ui.sectorsection.selects-the-attack-rate": "wählt die Ausnahmen der Angriffsrate, die für diese Studie gelten",
    "ui.sectorsection.without-a-sector-the": "Ohne Branche benutzt die Quantification die veröffentlichten Basisraten unverändert. Eine zu wählen ändert die Angriffsrate nur dort, wo eine dokumentierte Abweichung vorliegt.",

    // ── study ──
    "ui.study.export-import": "Export / Import",
    "ui.study.analysis-completeness-checks": "Vollständigkeitsprüfungen der Analyse",
    "ui.study.checks": "Prüfungen",
    "ui.study.copied": "Kopiert",
    "ui.study.copy-for-llm": "Für LLM kopieren",
    "ui.study.copy-this-workshop-as": "Diesen Workshop als LLM-tauglichen Kontext kopieren",
    "ui.study.download-markdown": "Markdown herunterladen",
    "ui.study.event-chains": "Ereignisketten",
    "ui.study.flow": "Flow",
    "ui.study.generate-a-report-of": "Einen Report dieser Studie erzeugen",
    "ui.study.graph": "Graph",
    "ui.study.open-in-browser-html": "Im Browser öffnen (HTML)",
    "ui.study.relationships": "Beziehungen",
    "ui.study.rendered-print-ready-new": "gesetzt · druckfertig · neuer Reiter",
    "ui.study.report": "Report",
    "ui.study.this-method": "Diese Methode",

    // ── tabletools ──
    "ui.tabletools.no-grouping": "keine Gruppierung",
    "ui.tabletools.clear-every-filter": "Alle Filter zurücksetzen",
    "ui.tabletools.group-by": "Gruppieren nach",
    "ui.tabletools.group-the-rows-by": "Die Zeilen nach einer Spalte gruppieren",

    // ── taxonomy ──
    "ui.taxonomy.import-export": "Import / Export",
    "ui.taxonomy.accent-color-css": "Akzentfarbe (CSS)",
    "ui.taxonomy.cancel": "Abbrechen",
    "ui.taxonomy.create": "Anlegen",
    "ui.taxonomy.delete-entity-type": "Entity type löschen",
    "ui.taxonomy.entity-type": "Entity type",
    "ui.taxonomy.field": "Field",
    "ui.taxonomy.fields": "Fields",
    "ui.taxonomy.group": "Group",
    "ui.taxonomy.label": "Label",
    "ui.taxonomy.meta-schema": "Meta-Schema",
    "ui.taxonomy.new-entity-type": "Neuer Entity type",
    "ui.taxonomy.new-group-tab": "Neue Group (Reiter)",
    "ui.taxonomy.plural": "Plural",
    "ui.taxonomy.remove-field": "Field entfernen",
    "ui.taxonomy.reset-default": "Auf Vorgabe zurücksetzen",
    "ui.taxonomy.select-or-create-an": "Wählen oder legen Sie einen Entity type an.",
    "ui.taxonomy.taxonomy": "Taxonomy",

    // ── taxonomyexplorer ──
    "ui.taxonomyexplorer.classes": "Klassen",
    "ui.taxonomyexplorer.groups-types-and-fields": "Gruppen, Typen und Felder, mit dem, was die Studie hält",
    "ui.taxonomyexplorer.outline": "Überblick",
    "ui.taxonomyexplorer.relations": "Beziehungen",
    "ui.taxonomyexplorer.the-published-class-hierarchy": "Die veröffentlichte Klassenhierarchie und was jede Klasse trägt",
    "ui.taxonomyexplorer.which-type-points-at": "Welcher Typ auf welchen zeigt",
    "ui.taxonomyexplorer.close": "Schließen",
    "ui.taxonomyexplorer.fields-the-published-catalogue": "Felder, die der veröffentlichte Katalog selbst füllt; die übrigen hält diese Anwendung daneben",
    "ui.taxonomyexplorer.filled-by-the-published": "Vom veröffentlichten Katalog gefüllt - zu ändern durch den Herausgeber",
    "ui.taxonomyexplorer.only-the-classes-this": "Nur die Klassen, die diese Studie verwendet",
    "ui.taxonomyexplorer.open": "Öffnen",
    "ui.taxonomyexplorer.own": "Eigene",
    "ui.taxonomyexplorer.search-the-model": "Im Modell suchen…",
    "ui.taxonomyexplorer.search-the-model-2": "Im Modell suchen",
    "ui.taxonomyexplorer.the-published-method": "Die veröffentlichte Methode",
    "ui.taxonomyexplorer.this-taxonomy-declares-no": "Diese Taxonomie deklariert keine Klassifikation mit einer Hierarchie.",

    // ── threatactorradar ──
    "ui.threatactorradar.actors-compared-across-ebios": "Akteure im Vergleich über die EBIOS-Bewertungen",
    "ui.threatactorradar.threat-landscape": "Bedrohungslage",

    // ── timeline ──
    "ui.timeline.every-change-across": "Jede Änderung an „{0}“, die neueste zuerst - über eine Hashkette gegen Veränderung gesichert.",
    "ui.timeline.open-this-record-s": "Den Änderungslauf dieses Datensatzes öffnen",
    "ui.timeline.this-record-no-longer": "Diesen Datensatz gibt es nicht mehr",
    "ui.timeline.change-timeline": "Änderungsverlauf",
    "ui.timeline.no-active-study-open": "Keine aktive Studie. Öffnen Sie eine Studie, um ihren Änderungsverlauf zu sehen.",
    "ui.timeline.no-changes-recorded-yet": "Noch keine Änderungen aufgezeichnet. Bearbeiten Sie eine Entität (mit Bearbeitername und optionaler Notiz), dann erscheint sie hier.",

    // ── ui ──
    "ui.ui.close": "Schließen",

    // ── vocabularysync ──
    "ui.vocabularysync.from-source-taken-on": "Aus {0}{1}, geholt am {2}. Die Prüfung ergänzt, was der Herausgeber seither hinzugefügt hat.",
    "ui.vocabularysync.version": ", Version ",
    "ui.vocabularysync.checking-asks-the-publisher": "Die Prüfung fragt beim Herausgeber die aktuellen Listen ab und ergänzt, was neu ist.",
    "ui.vocabularysync.vocabularies": "Vokabulare",

    // ── report ──
    "ui.report.organization": "Institution",
    "ui.report.scope": "Geltungsbereich",
    "ui.report.attack-paths-origin-action": "Angriffspfade (Ursprung -> Handlung -> Ergebnis)",
    "ui.report.change-record": "Änderungsnachweis",
    "ui.report.compliance-coverage": "Abdeckung der Compliance",
    "ui.report.date": "Datum",
    "ui.report.document-control": "Dokumentenlenkung",
    "ui.report.editor": "Bearbeiter",
    "ui.report.generated": "Erzeugt",
    "ui.report.kill-chain-mitigation-coverage": "Abdeckung der Kettenverteidigung",
    "ui.report.overview": "Überblick",
    "ui.report.reason": "Grund",
    "ui.report.record": "Datensatz",
    "ui.report.risk-matrix": "Risikomatrix",
    "ui.report.risk-treatment": "Risikobehandlung",
    "ui.report.threat-landscape-attacker-profiles": "Bedrohungslage und Angreiferprofile",
    "ui.report.vocabulary": "Vokabular",
    "ui.report.n-not-printed": "{0} nicht gedruckt: hier als nicht zutreffend entschieden.",
    "ui.report.treatment-decision-per-risk": "Behandlungsentscheidung je Risiko (strategisches Szenario). Das Restrisiko wird ABGELEITET aus der Entscheidung und daraus, wie weit die Angriffskette des Risikos bereits gemindert ist - Reduce senkt die Eintrittswahrscheinlichkeit um diese Abdeckung, Share senkt die Schwere, Accept behält den Ausgangswert, Avoid entfernt es.",
    "ui.report.changes": "Änderungen",
    "ui.report.changes-of-record": "Änderungen am Datenbestand",
    "ui.report.content": "Inhalt",
    "ui.report.document": "Dokument",
    "ui.report.generated-with": "Erzeugt mit {0} - {1}, offline.",
    "ui.report.licence": "Lizenz",
    "ui.report.no": "nein",
    "ui.report.none": "keine",
    "ui.report.rights-holder": "Rechteinhaber",
    "ui.report.sources-and-terms": "Quellen und Begriffe",
    "ui.report.yes": "ja",

    // ── the engine's own completeness checks; the two this profile switches off are left out ──
    "check.actor-no-category.title": "Risk sources ohne Category",
    "check.actor-no-category.hint": "Die Category bestimmt, wie oft ein Akteur dieser Art überhaupt angreift — eine kriminelle Gruppe und ein staatlicher Akteur unterscheiden sich um mehr als eine Größenordnung.",
    "check.asset-no-feared.title": "Business assets ohne Feared event",
    "check.asset-no-feared.hint": "Benennen Sie zu jedem Business asset, was schiefgehen könnte (ein Feared event).",
    "check.chain-detection-only.title": "Kill chains, die allein durch Detection verteidigt sind",
    "check.chain-detection-only.hint": "Diese Ketten werden allein durch Detection verteidigt; entdeckt zu werden hält allein noch niemanden auf.",
    "check.chain-no-prerequisites.title": "Kill chains, die als gerade Linie modelliert sind",
    "check.chain-no-prerequisites.hint": "Kein Schritt dieser Ketten nennt seine Voraussetzungen, die Kette wird also als Reihenfolge gelesen. Setzen Sie „preceded by“, wo ein Schritt wirklich auf einem anderen aufbaut.",
    "check.chain-nothing-stops.title": "Kill chains, die nichts blockiert oder entdeckt",
    "check.chain-nothing-stops.hint": "Auf diesen Ketten hält nichts einen Versuch auf — jeder Angreifer, der beginnt, kommt durch.",
    "check.damage-control-only.title": "Kill-chain-Schritte, an denen nichts blockiert oder entdeckt",
    "check.damage-control-only.hint": "An diesen Schritten hängt nichts, was blockiert oder entdeckt — sie kosten einen Angreifer nichts.",
    "check.detection-no-response.title": "Überwachte Ketten ohne Möglichkeit zu reagieren",
    "check.detection-no-response.hint": "Diese Ketten tragen detective Maßnahmen, aber keine corrective — das Modell schreibt ihnen daher fast keine Reaktionsfähigkeit zu.",
    "check.empty-opscenario.title": "Operational scenarios ohne Kill-chain-Schritte",
    "check.empty-opscenario.hint": "Modellieren Sie die Kill chain (Schritte + Tactics) für jedes Operational scenario.",
    "check.entry-no-technique.title": "Ketten, deren erster Schritt keine Technique nennt",
    "check.entry-no-technique.hint": "Die Einstiegs-Technique entscheidet zweierlei zugleich: wie oft der Akteur überhaupt in Kontakt kommt, und wie viel Können der erste Fuß in der Tür verlangt.",
    "check.feared-unused.title": "Feared events, die mit keinem Strategic scenario verknüpft sind",
    "check.feared-unused.hint": "Verbinden Sie jedes Feared event mit dem Szenario oder den Szenarien, die es auslösen würden.",
    "check.measure-dangling.title": "Security measures ohne Ziel",
    "check.measure-dangling.hint": "Richten Sie jede Maßnahme auf die Schritte, die sie abdeckt, die Assets, die sie schützt, oder die Requirements, die sie erfüllt.",
    "check.measure-unclassified.title": "Security measures ohne Effect class",
    "check.measure-unclassified.hint": "Setzen Sie den Maßnahmentyp. Die Quantification leitet die Wirkung eines Controls daraus ab — ein corrective Control mindert den Schaden, ein detective kann die Kette brechen.",
    "check.orphan-support.title": "Supporting assets ohne Verknüpfung zu einem Business asset",
    "check.orphan-support.hint": "Verknüpfen Sie jedes Supporting asset mit dem Business asset, das es trägt.",
    "check.reduce-without-measures.title": "Risiken als „Reduce“ behandelt, ohne dass etwas sie reduziert",
    "check.reduce-without-measures.hint": "Die Entscheidung lautet auf Reduktion, aber an keinem Schritt der Ketten hinter diesem Risiko hängt eine Maßnahme. Entweder die Maßnahme anhängen oder die Entscheidung ändern.",
    "check.source-unused.title": "Risk sources, die in keinem Szenario benutzt werden",
    "check.source-unused.hint": "Bauen Sie entweder ein Szenario für die Risk source, oder entfernen Sie sie.",
    "check.step-no-tactic.title": "Kill-chain-Schritte ohne Tactic",
    "check.step-no-tactic.hint": "Ein Schritt ohne Tactic fehlt in der Tactic-Verteidigungsansicht. Setzen Sie die Tactic, damit der Schritt zählt.",
    "check.uncovered-steps.title": "Kill-chain-Schritte ohne Security measure",
    "check.uncovered-steps.hint": "Fügen Sie eine Security measure hinzu, die jeden offenen Schritt abdeckt, oder nehmen Sie die Lücke ausdrücklich in Kauf.",
    "check.unrefined-strategic.title": "Strategic scenarios ohne Operational scenario",
    "check.unrefined-strategic.hint": "Verfeinern Sie jedes Strategic scenario zu mindestens einem Operational scenario mit Kill chain.",
    "check.untreated-risk.title": "Risiken ohne Behandlungsentscheidung",
    "check.untreated-risk.hint": "Legen Sie eine Risikobehandlung fest (Reduce / Accept / Share / Avoid) samt Restrisikoniveau.",

    ...GEN_WORDS_DE,
  },
};
